  ALG: {
    A01: {
      code: "A01",
      materia: "Álgebra Lineal",
      title: "Vectores y combinaciones lineales",
      fuente: "MIT 18.06SC — The Geometry of Linear Equations | 3Blue1Brown cap. 1-2",
      theory: ["Un vector es una flecha desde el origen: [3, 2] es \"3 a la derecha, 2 arriba\". Pero también es una lista de números que podés sumar componente a componente y escalar (multiplicar por un número). Esas dos operaciones — sumar y escalar — son TODO el álgebra lineal, como insiste 3Blue1Brown.", "Una combinación lineal de vectores v y w es a·v + b·w: los estirás por un número y los sumás. Pensá el stock de una sucursal como un vector [gaseosas, aguas, snacks]: sumar el stock de dos sucursales es sumar sus vectores; duplicar un pedido es escalar el vector."],
      example: "# Suma de vectores y escalado, componente a componente\ndef sumar(v, w):\n    return [a + b for a, b in zip(v, w)]\n\ndef escalar(k, v):\n    return [k * a for a in v]\n\nstock_norte = [40, 12, 8]   # [gaseosas, aguas, snacks]\nstock_sur = [15, 30, 5]\nprint(\"Stock total:\", sumar(stock_norte, stock_sur))\nprint(\"Pedido doble del Norte:\", escalar(2, stock_norte))",
      quiz: [{ q: "¿Cuáles son las dos operaciones fundamentales del álgebra lineal?", opts: ["Multiplicar y dividir", "Sumar vectores y escalarlos", "Rotar y trasladar", "Derivar e integrar"], correct: 1 }, { q: "La combinación lineal 2·[1,0] + 3·[0,1] da:", opts: ["[2,3]", "[3,2]", "[5,5]", "[2,0]"], correct: 0 }],
      exercise: {
        prompt: "Escribí una función combinacion(a, v, b, w) que devuelva la combinación lineal a·v + b·w de dos vectores (listas de igual longitud).",
        starter: "def combinacion(a, v, b, w):\n    # tu código acá\n    pass",
        tests: "assert combinacion(2, [1,0], 3, [0,1]) == [2, 3], \"2*[1,0]+3*[0,1]\"\nassert combinacion(1, [40,12], 1, [15,30]) == [55, 42], \"Suma de stock\"\nassert combinacion(0, [9,9], 5, [1,2]) == [5, 10], \"Anular el primero\"\nprint(\"TESTS_OK\")",
      },
    },
    A02: {
      code: "A02",
      materia: "Álgebra Lineal",
      title: "Producto matriz-vector y span",
      fuente: "MIT 18.06SC — The Geometry of Linear Equations | 3Blue1Brown cap. 3",
      theory: ["Multiplicar una matriz por un vector es tomar una combinación lineal de las columnas de la matriz, con pesos dados por el vector. A·x = x1·(columna 1) + x2·(columna 2) + ... Esta es LA idea que 3Blue1Brown pone en el centro: la matriz transforma el espacio, y A·x te dice a dónde va a parar x.", "El span de un conjunto de vectores es todo lo que podés alcanzar con sus combinaciones lineales. Dos vectores no alineados en el plano tienen span = todo el plano; si están alineados, su span es apenas una recta."],
      example: "# A·x como combinación lineal de las columnas de A\ndef matriz_por_vector(A, x):\n    # A es lista de FILAS; el resultado es un vector\n    return [sum(A[i][j] * x[j] for j in range(len(x))) for i in range(len(A))]\n\nA = [[1, 2],\n     [3, 4]]\nx = [1, 1]\nprint(\"A·x =\", matriz_por_vector(A, x))  # columna1 + columna2 = [3, 7]",
      quiz: [{ q: "Multiplicar A·x equivale a:", opts: ["Sumar todas las filas de A", "Una combinación lineal de las columnas de A con pesos x", "El determinante de A", "Escalar x por 2"], correct: 1 }, { q: "El span de dos vectores alineados (uno múltiplo del otro) es:", opts: ["Todo el plano", "Una recta", "Un solo punto", "El espacio 3D"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función matriz_por_vector(A, x) que multiplique la matriz A (lista de filas) por el vector x y devuelva el vector resultante.",
        starter: "def matriz_por_vector(A, x):\n    # tu código acá\n    pass",
        tests: "assert matriz_por_vector([[1,2],[3,4]], [1,1]) == [3, 7], \"columna1+columna2\"\nassert matriz_por_vector([[1,0],[0,1]], [5,9]) == [5, 9], \"Identidad no cambia x\"\nassert matriz_por_vector([[2,0],[0,2]], [3,4]) == [6, 8], \"Escala por 2\"\nprint(\"TESTS_OK\")",
      },
    },
    A03: {
      code: "A03",
      materia: "Álgebra Lineal",
      title: "Independencia lineal, base y dimensión",
      fuente: "MIT 18.06SC — Independence, Basis and Dimension | 3Blue1Brown cap. 2",
      theory: ["Un conjunto de vectores es linealmente independiente si ninguno es combinación lineal de los otros — ninguno es \"redundante\". Si uno se puede armar con los demás, es dependiente y no aporta dirección nueva.", "Una base es un conjunto de vectores independientes que generan todo el espacio (su span es todo). La cantidad de vectores de una base es la dimensión. En el plano, cualquier par de vectores no alineados es una base: dimensión 2."],
      example: "# Dos vectores son dependientes si uno es múltiplo del otro (caso 2D)\ndef son_dependientes_2d(v, w):\n    # dependientes si el determinante 2x2 es 0\n    return v[0]*w[1] - v[1]*w[0] == 0\n\nprint(\"[1,2] y [2,4]:\", son_dependientes_2d([1,2], [2,4]))  # True: w = 2v\nprint(\"[1,0] y [0,1]:\", son_dependientes_2d([1,0], [0,1]))  # False: base",
      quiz: [{ q: "Un conjunto de vectores es linealmente independiente si:", opts: ["Todos son iguales", "Ninguno es combinación lineal de los otros", "Suman cero", "Son ortogonales"], correct: 1 }, { q: "La dimensión de un espacio es:", opts: ["La cantidad de vectores que tenés", "La cantidad de vectores de una base", "La longitud del vector más largo", "Siempre 3"], correct: 1 }],
      exercise: {
        prompt: "En 2D, dos vectores [a,b] y [c,d] son dependientes si a·d − b·c = 0. Escribí son_dependientes(v, w) que devuelva True si los vectores 2D v y w son linealmente dependientes.",
        starter: "def son_dependientes(v, w):\n    # tu código acá\n    pass",
        tests: "assert son_dependientes([1,2], [2,4]) == True, \"[2,4] = 2*[1,2]\"\nassert son_dependientes([1,0], [0,1]) == False, \"Base canónica: independientes\"\nassert son_dependientes([3,6], [1,2]) == True, \"Múltiplos\"\nprint(\"TESTS_OK\")",
      },
    },
    A04: {
      code: "A04",
      materia: "Álgebra Lineal",
      title: "Multiplicación de matrices como composición",
      fuente: "MIT 18.06SC — Multiplication and Inverse Matrices | 3Blue1Brown cap. 4",
      theory: ["Multiplicar dos matrices A·B significa aplicar primero la transformación B y después A — es COMPOSICIÓN de transformaciones, la idea central de la clase 4 de Strang y del cap. 4 de 3Blue1Brown. Por eso el orden importa: A·B casi nunca es igual a B·A.", "Mecánicamente, la entrada (i,j) del producto es el producto punto de la fila i de A con la columna j de B. Es como aplicar dos ajustes de stock en cadena: el resultado depende de cuál hacés primero."],
      example: "# Producto de matrices: (fila de A) · (columna de B)\ndef multiplicar(A, B):\n    n, m, p = len(A), len(B), len(B[0])\n    return [[sum(A[i][k]*B[k][j] for k in range(m)) for j in range(p)] for i in range(n)]\n\nA = [[1, 2], [0, 1]]\nB = [[1, 0], [3, 1]]\nprint(\"A·B =\", multiplicar(A, B))\nprint(\"B·A =\", multiplicar(B, A))  # distinto: el orden importa",
      quiz: [{ q: "El producto de matrices A·B representa:", opts: ["Sumar A y B", "Aplicar B y después A (composición)", "El promedio de A y B", "Siempre lo mismo que B·A"], correct: 1 }, { q: "La entrada (i,j) de A·B es:", opts: ["A[i][j] + B[i][j]", "El producto punto de la fila i de A con la columna j de B", "A[i][j] · B[i][j]", "La suma de la fila i"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función multiplicar(A, B) que devuelva el producto de dos matrices (listas de filas) compatibles.",
        starter: "def multiplicar(A, B):\n    # tu código acá\n    pass",
        tests: "assert multiplicar([[1,2],[0,1]], [[1,0],[3,1]]) == [[7,2],[3,1]], \"Fallo caso 1\"\nassert multiplicar([[1,0],[0,1]], [[5,6],[7,8]]) == [[5,6],[7,8]], \"Identidad\"\nprint(\"TESTS_OK\")",
      },
    },
    A05: {
      code: "A05",
      materia: "Álgebra Lineal",
      title: "Sistemas y eliminación de Gauss",
      fuente: "MIT 18.06SC — Elimination with Matrices | 3Blue1Brown cap. 3 (contexto)",
      theory: ["Resolver un sistema de ecuaciones es encontrar el vector x tal que A·x = b. La eliminación de Gauss lo logra restando múltiplos de una fila a las otras para dejar ceros debajo de la diagonal (forma triangular), y después despejando de abajo hacia arriba.", "Es el mismo método que aprendiste en el secundario para resolver dos ecuaciones con dos incógnitas, pero sistematizado para que una computadora lo haga con cientos de variables. Strang lo presenta como la operación de trabajo del álgebra lineal computacional."],
      example: "# Un paso de eliminación: dejar un 0 en A[1][0]\nA = [[2, 1],\n     [4, 3]]\nb = [5, 11]\nfactor = A[1][0] / A[0][0]        # 4/2 = 2\nA[1] = [A[1][j] - factor*A[0][j] for j in range(2)]\nb[1] = b[1] - factor*b[0]\nprint(\"A triangular:\", A)         # [[2,1],[0,1]]\nprint(\"b:\", b)                    # [5, 1]  ->  x2 = 1, luego x1 = 2",
      quiz: [{ q: "Resolver A·x = b significa encontrar:", opts: ["El determinante", "El vector x que cumple la ecuación", "La inversa de b", "Las columnas de A"], correct: 1 }, { q: "La eliminación de Gauss busca dejar la matriz en forma:", opts: ["Diagonal de unos", "Triangular (ceros debajo de la diagonal)", "Toda de ceros", "Simétrica"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función eliminar_paso(A, b, i, j) que reste a la fila i el múltiplo de la fila j necesario para dejar A[i][j] = 0, aplicando el mismo factor a b. Devolvé la tupla (A, b) modificada. Asumí A[j][j] != 0.",
        starter: "def eliminar_paso(A, b, i, j):\n    # tu código acá\n    pass",
        tests: "A = [[2,1],[4,3]]; b = [5,11]\nA2, b2 = eliminar_paso(A, b, 1, 0)\nassert A2[1] == [0, 1], \"Debe dejar 0 en A[1][0]\"\nassert b2[1] == 1, \"b actualizado\"\nprint(\"TESTS_OK\")",
      },
    },
    A06: {
      code: "A06",
      materia: "Álgebra Lineal",
      title: "La matriz inversa",
      fuente: "MIT 18.06SC — Multiplication and Inverse Matrices | 3Blue1Brown cap. 7 (inverse, column space)",
      theory: ["La inversa de A, escrita A⁻¹, es la matriz que deshace lo que A hace: A·A⁻¹ = I (la identidad). Si A transforma el espacio, A⁻¹ lo devuelve a como estaba. Con ella, resolver A·x = b es directo: x = A⁻¹·b.", "No toda matriz tiene inversa: 3Blue1Brown lo explica hermoso — si A aplasta el espacio a una dimensión menor (determinante 0), la información se pierde y no hay forma de deshacerla. Para una matriz 2×2 [[a,b],[c,d]], la inversa existe si ad − bc ≠ 0."],
      example: "# Inversa de una matriz 2x2 (si el determinante no es 0)\ndef inversa_2x2(A):\n    a, b = A[0]\n    c, d = A[1]\n    det = a*d - b*c\n    if det == 0:\n        return None\n    return [[ d/det, -b/det],\n            [-c/det,  a/det]]\n\nA = [[4, 7], [2, 6]]\nprint(\"A⁻¹ =\", inversa_2x2(A))",
      quiz: [{ q: "La inversa A⁻¹ cumple que:", opts: ["A + A⁻¹ = 0", "A · A⁻¹ = I (identidad)", "A⁻¹ = 2A", "A⁻¹ = Aᵀ siempre"], correct: 1 }, { q: "Una matriz 2×2 tiene inversa cuando:", opts: ["Sus filas son iguales", "Su determinante ad−bc ≠ 0", "Todos sus valores son positivos", "Es simétrica"], correct: 1 }],
      exercise: {
        prompt: "Escribí inversa_2x2(A) que devuelva la inversa de una matriz 2×2 [[a,b],[c,d]] como [[d/det,-b/det],[-c/det,a/det]] con det=ad−bc, o None si det es 0.",
        starter: "def inversa_2x2(A):\n    # tu código acá\n    pass",
        tests: "r = inversa_2x2([[4,7],[2,6]])\nassert r == [[0.6, -0.7], [-0.2, 0.4]], \"Inversa incorrecta\"\nassert inversa_2x2([[1,2],[2,4]]) is None, \"Determinante 0: sin inversa\"\nprint(\"TESTS_OK\")",
      },
    },
    A07: {
      code: "A07",
      materia: "Álgebra Lineal",
      title: "Espacio columna y espacio nulo",
      fuente: "MIT 18.06SC — Column Space and Nullspace | 3Blue1Brown cap. 7-8",
      theory: ["El espacio columna de A es el span de sus columnas: todos los b para los que A·x = b tiene solución. Si b no está en el espacio columna, el sistema no tiene solución — no hay combinación de las columnas que lo alcance.", "El espacio nulo es el conjunto de todos los x tales que A·x = 0. Siempre contiene al vector cero; si contiene algo más, significa que las columnas son dependientes. 3Blue1Brown lo llama el \"kernel\": lo que la transformación aplasta al origen."],
      example: "# ¿Está el vector cero en el espacio nulo? (siempre sí)\ndef matriz_por_vector(A, x):\n    return [sum(A[i][j]*x[j] for j in range(len(x))) for i in range(len(A))]\n\nA = [[1, 2], [2, 4]]   # columnas dependientes\nx_cero = [0, 0]\nprint(\"A·0 =\", matriz_por_vector(A, x_cero))\n# [1,-0.5] escalado: probamos un x no trivial del espacio nulo\nx = [2, -1]\nprint(\"A·[2,-1] =\", matriz_por_vector(A, x))  # [0,0]: x está en el espacio nulo",
      quiz: [{ q: "El espacio columna de A contiene:", opts: ["Todos los x posibles", "Todos los b para los que A·x=b tiene solución", "Solo el vector cero", "Las filas de A"], correct: 1 }, { q: "El espacio nulo de A es el conjunto de x tales que:", opts: ["A·x = b", "A·x = 0", "x = 0 únicamente", "A·x = x"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función esta_en_nulo(A, x) que devuelva True si A·x da el vector cero (es decir, x está en el espacio nulo de A).",
        starter: "def esta_en_nulo(A, x):\n    # tu código acá\n    pass",
        tests: "assert esta_en_nulo([[1,2],[2,4]], [2,-1]) == True, \"[2,-1] anula A\"\nassert esta_en_nulo([[1,2],[2,4]], [0,0]) == True, \"El cero siempre está\"\nassert esta_en_nulo([[1,2],[2,4]], [1,1]) == False, \"[1,1] no se anula\"\nprint(\"TESTS_OK\")",
      },
    },
    A08: {
      code: "A08",
      materia: "Álgebra Lineal",
      title: "Los cuatro subespacios fundamentales",
      fuente: "MIT 18.06SC — The Four Fundamental Subspaces | 3Blue1Brown cap. 8 (contexto)",
      theory: ["Toda matriz A define cuatro subespacios: el espacio columna y el espacio nulo (ya vistos), más el espacio fila (span de las filas) y el espacio nulo izquierdo. Es el \"teorema fundamental del álgebra lineal\" que Strang considera el corazón del curso.", "La relación clave, que resume toda la Unidad I: el rango r (cantidad de columnas independientes) determina las dimensiones de los cuatro. Para una matriz de n columnas, dim(espacio columna) = r y dim(espacio nulo) = n − r. Lo que no aporta dirección nueva, va al espacio nulo."],
      example: "# El rango = cantidad de columnas independientes (caso 2x2 simple)\ndef rango_2x2(A):\n    # si las dos columnas son dependientes, rango 1; si no, rango 2\n    a, b = A[0]\n    c, d = A[1]\n    return 2 if (a*d - b*c) != 0 else 1\n\nprint(\"Rango de [[1,2],[3,4]]:\", rango_2x2([[1,2],[3,4]]))  # 2\nprint(\"Rango de [[1,2],[2,4]]:\", rango_2x2([[1,2],[2,4]]))  # 1 (dependientes)",
      quiz: [{ q: "¿Cuántos subespacios fundamentales define toda matriz?", opts: ["2", "3", "4", "Depende del tamaño"], correct: 2 }, { q: "Para una matriz de n columnas y rango r, la dimensión del espacio nulo es:", opts: ["r", "n", "n − r", "n + r"], correct: 2 }],
      exercise: {
        prompt: "Para una matriz 2×2, el rango es 2 si el determinante ad−bc ≠ 0, y 1 si es 0 (asumiendo que no es la matriz nula). Escribí rango_2x2(A) que lo devuelva.",
        starter: "def rango_2x2(A):\n    # tu código acá\n    pass",
        tests: "assert rango_2x2([[1,2],[3,4]]) == 2, \"Independientes\"\nassert rango_2x2([[1,2],[2,4]]) == 1, \"Dependientes\"\nprint(\"TESTS_OK\")",
      },
    },
    A09: {
      code: "A09",
      materia: "Álgebra Lineal",
      title: "Producto interno, longitud y ortogonalidad",
      fuente: "MIT 18.06SC — Orthogonal Vectors and Subspaces | 3Blue1Brown cap. 9",
      theory: ["El producto interno (o producto punto) de dos vectores es la suma de sus productos componente a componente: [a,b]·[c,d] = a·c + b·d. Da un número, y ese número mide cuánto \"apuntan en la misma dirección\" dos vectores.", "Dos vectores son ortogonales (perpendiculares) si su producto interno es 0. Y la longitud de un vector es la raíz de su producto interno consigo mismo: |v| = √(v·v), que es Pitágoras en n dimensiones. 3Blue1Brown conecta el producto punto con la proyección — la base de la próxima lección."],
      example: "# Producto punto, longitud y test de ortogonalidad\nimport math\n\ndef punto(v, w):\n    return sum(a*b for a, b in zip(v, w))\n\ndef longitud(v):\n    return math.sqrt(punto(v, v))\n\nprint(\"[1,2]·[3,4] =\", punto([1,2], [3,4]))       # 11\nprint(\"|[3,4]| =\", longitud([3,4]))               # 5.0\nprint(\"¿[1,0]⊥[0,1]?:\", punto([1,0], [0,1]) == 0)  # True",
      quiz: [{ q: "El producto interno de [2,3] y [4,1] es:", opts: ["11", "8", "14", "5"], correct: 0 }, { q: "Dos vectores son ortogonales cuando su producto interno es:", opts: ["1", "0", "Negativo", "Su longitud"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función son_ortogonales(v, w) que devuelva True si el producto interno de v y w (vectores de igual longitud) es 0.",
        starter: "def son_ortogonales(v, w):\n    # tu código acá\n    pass",
        tests: "assert son_ortogonales([1,0], [0,1]) == True, \"Ejes perpendiculares\"\nassert son_ortogonales([1,2], [2,-1]) == True, \"1*2 + 2*(-1) = 0\"\nassert son_ortogonales([1,1], [1,1]) == False, \"Producto = 2\"\nprint(\"TESTS_OK\")",
      },
    },
    A10: {
      code: "A10",
      materia: "Álgebra Lineal",
      title: "Proyecciones",
      fuente: "MIT 18.06SC — Projections onto Subspaces | 3Blue1Brown cap. 9",
      theory: ["Proyectar un vector b sobre otro vector a es encontrar la \"sombra\" de b en la dirección de a: el punto de la recta de a más cercano a b. La fórmula sale del producto interno: la proyección es (a·b / a·a) · a.", "¿Por qué importa? Porque cuando un sistema A·x = b NO tiene solución (b no está en el espacio columna), lo mejor que podés hacer es proyectar b sobre el espacio columna y resolver eso. Esa es la idea de mínimos cuadrados de la próxima lección — el motor del ajuste de datos en estadística y ML."],
      example: "# Proyección de b sobre la dirección de a\ndef punto(v, w):\n    return sum(x*y for x, y in zip(v, w))\n\ndef proyeccion(a, b):\n    escala = punto(a, b) / punto(a, a)\n    return [escala * ai for ai in a]\n\nprint(\"Proyección de [1,1] sobre [2,0]:\", proyeccion([2,0], [1,1]))  # [1.0, 0.0]",
      quiz: [{ q: "La proyección de b sobre a es:", opts: ["a + b", "(a·b / a·a) · a", "El producto punto a·b", "b − a"], correct: 1 }, { q: "¿Para qué sirve proyectar cuando A·x=b no tiene solución?", opts: ["Para nada", "Para encontrar la mejor solución aproximada (mínimos cuadrados)", "Para invertir A", "Para calcular el determinante"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función proyeccion(a, b) que devuelva la proyección del vector b sobre la dirección del vector a, usando (a·b / a·a)·a.",
        starter: "def proyeccion(a, b):\n    # tu código acá\n    pass",
        tests: "assert proyeccion([2,0], [1,1]) == [1.0, 0.0], \"Sombra sobre el eje x\"\nassert proyeccion([1,1], [2,0]) == [1.0, 1.0], \"Sombra sobre la diagonal\"\nprint(\"TESTS_OK\")",
      },
    },
    A11: {
      code: "A11",
      materia: "Álgebra Lineal",
      title: "Mínimos cuadrados",
      fuente: "MIT 18.06SC — Projection Matrices and Least Squares | PS Unidad II",
      theory: ["Cuando tenés más ecuaciones que incógnitas (más datos que parámetros), casi nunca hay una recta que pase por todos los puntos. Mínimos cuadrados encuentra la recta que MINIMIZA la suma de los errores al cuadrado — la \"mejor\" en el sentido de la menor distancia total.", "Es la técnica detrás de la regresión lineal que vas a ver en ML: ajustar una tendencia a datos ruidosos. La conexión con álgebra lineal es directa — minimizar el error al cuadrado es proyectar el vector de datos sobre el espacio columna, exactamente lo de la lección anterior."],
      example: "# Ajuste de una recta y = m·x + c por mínimos cuadrados (fórmula cerrada 1D)\ndef ajuste_recta(xs, ys):\n    n = len(xs)\n    sx, sy = sum(xs), sum(ys)\n    sxx = sum(x*x for x in xs)\n    sxy = sum(x*y for x, y in zip(xs, ys))\n    m = (n*sxy - sx*sy) / (n*sxx - sx*sx)\n    c = (sy - m*sx) / n\n    return m, c\n\n# Ventas que crecen con ruido\nm, c = ajuste_recta([1,2,3,4], [2,4,5,8])\nprint(f\"Mejor recta: y = {m:.2f}x + {c:.2f}\")",
      quiz: [{ q: "Mínimos cuadrados encuentra la recta que minimiza:", opts: ["La cantidad de puntos", "La suma de los errores al cuadrado", "La pendiente", "El determinante"], correct: 1 }, { q: "Mínimos cuadrados es la base de qué técnica de ML:", opts: ["Clustering", "Regresión lineal", "Árboles de decisión", "Redes neuronales"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función pendiente_minimos_cuadrados(xs, ys) que devuelva la pendiente m = (n·Σxy − Σx·Σy)/(n·Σx² − (Σx)²) del ajuste por mínimos cuadrados, redondeada a 4 decimales.",
        starter: "def pendiente_minimos_cuadrados(xs, ys):\n    # tu código acá\n    pass",
        tests: "assert pendiente_minimos_cuadrados([1,2,3,4], [2,4,6,8]) == 2.0, \"Recta perfecta y=2x\"\nassert pendiente_minimos_cuadrados([0,1,2], [1,2,3]) == 1.0, \"Pendiente 1\"\nprint(\"TESTS_OK\")",
      },
    },
    A12: {
      code: "A12",
      materia: "Álgebra Lineal",
      title: "El determinante",
      fuente: "MIT 18.06SC — Properties of Determinants + Determinant Formulas and Cofactors | 3Blue1Brown cap. 6",
      theory: ["El determinante de una matriz es un número que mide cuánto la transformación estira o encoge el área (en 2D) o el volumen (en 3D). 3Blue1Brown lo hace inolvidable: si det = 2, las áreas se duplican; si det = 0, todo se aplasta a una dimensión menor (y por eso no hay inversa).", "Para una matriz 2×2 [[a,b],[c,d]], el determinante es ad − bc. El signo indica si la transformación invierte la orientación (como un espejo). Es la misma cuenta que ya usaste para detectar dependencia lineal y para invertir: todo está conectado."],
      example: "# El determinante como factor de escala de área\ndef det_2x2(A):\n    return A[0][0]*A[1][1] - A[0][1]*A[1][0]\n\nprint(\"det[[3,0],[0,2]] =\", det_2x2([[3,0],[0,2]]))  # 6: área x6\nprint(\"det[[1,2],[2,4]] =\", det_2x2([[1,2],[2,4]]))  # 0: aplasta el espacio",
      quiz: [{ q: "El determinante mide:", opts: ["La suma de la diagonal", "Cuánto la transformación estira el área/volumen", "La longitud del vector", "El rango"], correct: 1 }, { q: "Si el determinante es 0, la matriz:", opts: ["Es la identidad", "No tiene inversa (aplasta el espacio)", "Es simétrica", "Tiene rango máximo"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función det_2x2(A) que devuelva el determinante ad−bc de una matriz 2×2 [[a,b],[c,d]].",
        starter: "def det_2x2(A):\n    # tu código acá\n    pass",
        tests: "assert det_2x2([[3,0],[0,2]]) == 6, \"Escala de área 6\"\nassert det_2x2([[1,2],[2,4]]) == 0, \"Singular\"\nassert det_2x2([[1,0],[0,1]]) == 1, \"Identidad no cambia área\"\nprint(\"TESTS_OK\")",
      },
    },
    A13: {
      code: "A13",
      materia: "Álgebra Lineal",
      title: "Autovalores y autovectores",
      fuente: "MIT 18.06SC — Eigenvalues and Eigenvectors | 3Blue1Brown cap. 14",
      theory: ["Un autovector de A es un vector especial que, al aplicarle la transformación A, NO cambia de dirección — solo se estira o encoge. Cuánto se estira es el autovalor λ. En fórmula: A·v = λ·v. 3Blue1Brown los muestra como los \"ejes\" que la transformación deja quietos.", "Son la herramienta más importante de la materia para IA: revelan la estructura profunda de una transformación. En una matriz de Markov modelan el estado de equilibrio; en PCA (que verás en ML) los autovectores de la matriz de covarianza son las direcciones de máxima variación de los datos."],
      example: "# Verificar que v es autovector de A con autovalor lambda\ndef matriz_por_vector(A, x):\n    return [sum(A[i][j]*x[j] for j in range(len(x))) for i in range(len(A))]\n\nA = [[2, 0], [0, 3]]   # diagonal: autovectores son los ejes\nv = [1, 0]             # eje x\nAv = matriz_por_vector(A, v)\nprint(\"A·[1,0] =\", Av, \"= 2·[1,0] -> autovalor 2\")",
      quiz: [{ q: "Un autovector de A cumple que A·v es:", opts: ["El vector cero", "λ·v (mismo vector, escalado)", "Perpendicular a v", "La identidad"], correct: 1 }, { q: "En PCA (ML), los autovectores dan:", opts: ["El promedio de los datos", "Las direcciones de máxima variación de los datos", "El error del modelo", "La cantidad de datos"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función es_autovector(A, v, lam) que devuelva True si A·v == lam·v (es decir, v es autovector de A con autovalor lam). Trabajá con enteros para comparación exacta.",
        starter: "def es_autovector(A, v, lam):\n    # tu código acá\n    pass",
        tests: "assert es_autovector([[2,0],[0,3]], [1,0], 2) == True, \"eje x, autovalor 2\"\nassert es_autovector([[2,0],[0,3]], [0,1], 3) == True, \"eje y, autovalor 3\"\nassert es_autovector([[2,0],[0,3]], [1,1], 2) == False, \"[1,1] no es autovector\"\nprint(\"TESTS_OK\")",
      },
    },
    A14: {
      code: "A14",
      materia: "Álgebra Lineal",
      title: "Diagonalización",
      fuente: "MIT 18.06SC — Diagonalization and Powers of A | 3Blue1Brown cap. 14",
      theory: ["Diagonalizar A es escribirla como A = S·Λ·S⁻¹, donde Λ es una matriz diagonal con los autovalores y S tiene los autovectores como columnas. Es cambiar a las \"coordenadas naturales\" de la transformación, donde todo se vuelve un simple estiramiento por eje.", "El pago enorme: elevar A a una potencia grande se vuelve trivial, porque Aⁿ = S·Λⁿ·S⁻¹ y elevar una diagonal es solo elevar cada autovalor. Así se calcula el estado a largo plazo de un proceso (una cadena de Markov de stock entre sucursales, por ejemplo) sin multiplicar la matriz mil veces."],
      example: "# Elevar una matriz diagonal es elevar cada elemento (la clave de diagonalizar)\ndef potencia_diagonal(diag, n):\n    return [d**n for d in diag]\n\nautovalores = [2, 3]\nprint(\"Λ^5 (diagonal):\", potencia_diagonal(autovalores, 5))  # [32, 243]",
      quiz: [{ q: "Diagonalizar A significa escribirla como:", opts: ["A = S + Λ", "A = S·Λ·S⁻¹ (autovectores y autovalores)", "A = Aᵀ", "A = 2A"], correct: 1 }, { q: "¿Por qué diagonalizar facilita calcular Aⁿ?", opts: ["Porque elevar una matriz diagonal es elevar cada autovalor", "Porque A se vuelve la identidad", "Porque n desaparece", "No lo facilita"], correct: 0 }],
      exercise: {
        prompt: "Escribí una función potencia_diagonal(diag, n) que reciba una lista con los elementos de la diagonal y devuelva la lista con cada elemento elevado a la n.",
        starter: "def potencia_diagonal(diag, n):\n    # tu código acá\n    pass",
        tests: "assert potencia_diagonal([2,3], 5) == [32, 243], \"2^5 y 3^5\"\nassert potencia_diagonal([1,0], 10) == [1, 0], \"1 y 0 a cualquier potencia\"\nprint(\"TESTS_OK\")",
      },
    },
    A15: {
      code: "A15",
      materia: "Álgebra Lineal",
      title: "Matrices simétricas y definidas positivas",
      fuente: "MIT 18.06SC — Symmetric Matrices and Positive Definiteness | 3Blue1Brown cap. 14 (contexto)",
      theory: ["Una matriz es simétrica si es igual a su transpuesta (A = Aᵀ): el valor en (i,j) es igual al de (j,i). Estas matrices son las mejores del álgebra lineal: sus autovalores son siempre reales y sus autovectores siempre ortogonales.", "Una matriz simétrica es definida positiva si todos sus autovalores son positivos — geométricamente, actúa siempre \"hacia afuera\", sin invertir ninguna dirección. Aparecen en todos lados en ML: las matrices de covarianza (base de PCA) son simétricas y semidefinidas positivas por construcción."],
      example: "# Verificar si una matriz es simétrica (A == A transpuesta)\ndef es_simetrica(A):\n    n = len(A)\n    return all(A[i][j] == A[j][i] for i in range(n) for j in range(n))\n\nprint(\"[[2,1],[1,3]] simétrica:\", es_simetrica([[2,1],[1,3]]))  # True\nprint(\"[[2,1],[0,3]] simétrica:\", es_simetrica([[2,1],[0,3]]))  # False",
      quiz: [{ q: "Una matriz es simétrica si:", opts: ["Todos sus valores son iguales", "A = Aᵀ (igual a su transpuesta)", "Su determinante es 1", "Es diagonal"], correct: 1 }, { q: "Las matrices de covarianza en ML (base de PCA) son:", opts: ["Siempre la identidad", "Simétricas y (semi)definidas positivas", "Antisimétricas", "Sin autovalores"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función es_simetrica(A) que devuelva True si la matriz cuadrada A es igual a su transpuesta (A[i][j] == A[j][i] para todo i, j).",
        starter: "def es_simetrica(A):\n    # tu código acá\n    pass",
        tests: "assert es_simetrica([[2,1],[1,3]]) == True, \"Simétrica\"\nassert es_simetrica([[2,1],[0,3]]) == False, \"No simétrica\"\nassert es_simetrica([[5]]) == True, \"1x1 siempre simétrica\"\nprint(\"TESTS_OK\")",
      },
    },
    A16: {
      code: "A16",
      materia: "Álgebra Lineal",
      title: "SVD: descomposición en valores singulares",
      fuente: "MIT 18.06SC — Singular Value Decomposition | 3Blue1Brown cap. 15-16 (contexto)",
      theory: ["La SVD escribe CUALQUIER matriz como A = U·Σ·Vᵀ: una rotación (Vᵀ), un estiramiento por ejes (Σ, diagonal con los valores singulares), y otra rotación (U). Es la generalización de los autovalores a matrices que no son cuadradas, y Strang la considera la culminación del curso.", "Es la herramienta más poderosa de la materia para IA: los valores singulares dicen cuánta \"información\" aporta cada dirección. Quedarte con los más grandes y descartar los chicos comprime datos perdiendo lo mínimo — es la base de la compresión de imágenes, los sistemas de recomendación y la reducción de dimensionalidad (PCA) que verás en ML."],
      example: "# Los valores singulares ordenados dicen qué direcciones conservar\n# (simulamos: en la práctica salen de la SVD; acá mostramos la idea de truncar)\nvalores_singulares = [9.5, 4.2, 0.8, 0.1]\ntotal = sum(valores_singulares)\nacumulado = 0\nfor i, s in enumerate(valores_singulares):\n    acumulado += s\n    print(f\"Con {i+1} componentes: {acumulado/total:.1%} de la información\")",
      quiz: [{ q: "La SVD descompone una matriz A como:", opts: ["A = S·Λ·S⁻¹", "A = U·Σ·Vᵀ (rotación, estiramiento, rotación)", "A = A·Aᵀ", "A = I"], correct: 1 }, { q: "¿Para qué sirve quedarse con los valores singulares más grandes?", opts: ["Para invertir A", "Para comprimir datos perdiendo lo mínimo (base de PCA)", "Para hacer A simétrica", "Para nada"], correct: 1 }],
      exercise: {
        prompt: "Los valores singulares miden información por dirección. Escribí una función energia_acumulada(valores, k) que devuelva qué fracción del total representan los primeros k valores singulares (suma de los primeros k sobre suma total), redondeada a 4 decimales.",
        starter: "def energia_acumulada(valores, k):\n    # tu código acá\n    pass",
        tests: "assert energia_acumulada([9.5, 4.2, 0.8, 0.1], 2) == 0.9384, \"Primeros 2 de 4\"\nassert energia_acumulada([5, 5], 1) == 0.5, \"Mitad\"\nassert energia_acumulada([1, 2, 3], 3) == 1.0, \"Todos\"\nprint(\"TESTS_OK\")",
      },
    },
    A17: {
      code: "A17",
      materia: "Álgebra Lineal",
      title: "Proyecto integrador",
      fuente: "MIT 18.06SC — Problem sets y exámenes de las 3 unidades (nivel de exigencia)",
      theory: ["Este integrador junta las piezas centrales de la materia sin librerías: operar con vectores y matrices, y aplicar el producto interno. Es el nivel de un examen de 18.06SC, resoluble a mano o en código.", "El caso combina lo visto: representar datos como vectores, multiplicar por una matriz de transformación, y medir con producto interno — el flujo exacto que hace una capa de una red neuronal (multiplicar por pesos) o una proyección de datos en PCA."],
      example: "# Las piezas del integrador: matriz·vector + producto interno\ndef matriz_por_vector(A, x):\n    return [sum(A[i][j]*x[j] for j in range(len(x))) for i in range(len(A))]\n\ndef punto(v, w):\n    return sum(a*b for a, b in zip(v, w))\n\nA = [[1, 0], [0, 2]]\nx = [3, 4]\ny = matriz_por_vector(A, x)\nprint(\"A·x =\", y, \"| |A·x|² =\", punto(y, y))",
      quiz: [{ q: "El flujo 'multiplicar por una matriz de pesos' es la operación central de:", opts: ["Un árbol de decisión", "Una capa de una red neuronal", "Una base de datos", "Un grafo"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función transformar_y_medir(A, x) que: (1) calcule y = A·x (matriz por vector), y (2) devuelva el producto interno de y consigo mismo (y·y, es decir la longitud al cuadrado del resultado). Todo sin librerías.",
        starter: "def transformar_y_medir(A, x):\n    # tu código acá\n    pass",
        tests: "assert transformar_y_medir([[1,0],[0,2]], [3,4]) == 73, \"y=[3,8], 9+64=73\"\nassert transformar_y_medir([[1,0],[0,1]], [3,4]) == 25, \"Identidad: 9+16=25\"\nassert transformar_y_medir([[0,0],[0,0]], [5,5]) == 0, \"Matriz nula\"\nprint(\"TESTS_OK\")",
      },
    },
  },