  MDIS: {
    M01: {
      code: "M01",
      materia: "Matemática Discreta",
      title: "Proposiciones y demostración directa",
      fuente: "MIT 6.042J — Lec 1: Introduction and proofs | Libro LLM cap. 1",
      theory: ["Una proposición es una afirmación que es verdadera o falsa, sin punto medio: \"el stock del depósito Norte es 0\" lo es; \"¿cuánto stock hay?\" no. Una demostración es un argumento que establece que una proposición es verdadera siempre, no solo en los casos que probaste.", "Acá está la trampa que abre el curso de MIT: probar muchos casos NO demuestra nada. El polinomio n² + n + 41 da primo para n = 0, 1, 2... ¡hasta 39! Y en n = 40 falla. Verificar ejemplos sirve para buscar contraejemplos, nunca para demostrar."],
      example: "# El polinomio de Euler: parece que siempre da primo... hasta que no.\ndef es_primo(n):\n    if n < 2:\n        return False\n    for d in range(2, int(n**0.5) + 1):\n        if n % d == 0:\n            return False\n    return True\n\nfor n in [0, 1, 2, 10, 39, 40]:\n    valor = n*n + n + 41\n    print(f\"n={n}: {valor} -> primo: {es_primo(valor)}\")",
      quiz: [{ q: "¿Cuál de estas es una proposición?", opts: ["¿Queda stock?", "Traé más cajas", "El lote 12 tiene 40 unidades", "Ojalá llegue el camión"], correct: 2 }, { q: "Verificar que una afirmación vale para 1000 casos...", opts: ["La demuestra", "No la demuestra, pero puede encontrar un contraejemplo", "La refuta", "Es lo mismo que una demostración"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función primer_contraejemplo(limite) que devuelva el primer n entre 0 y limite (inclusive) tal que n*n + n + 41 NO es primo, o -1 si no hay ninguno en ese rango. Podés reutilizar la idea de es_primo del ejemplo.",
        starter: "def primer_contraejemplo(limite):\n    # tu código acá\n    pass",
        tests: "assert primer_contraejemplo(50) == 40, \"El primer contraejemplo del polinomio de Euler es n=40\"\nassert primer_contraejemplo(30) == -1, \"Hasta 30 no hay contraejemplo\"\nprint(\"TESTS_OK\")",
      },
    },
    M02: {
      code: "M02",
      materia: "Matemática Discreta",
      title: "Lógica: conectivos y cuantificadores",
      fuente: "MIT 6.042J — Libro LLM cap. 3 (Logical Formulas; sin clase propia en F2010)",
      theory: ["Los conectivos combinan proposiciones: AND (las dos verdaderas), OR (al menos una), NOT (la invierte) e IMPLICA (p → q). La implicación es la más traicionera: solo es falsa cuando p es verdadera y q falsa. Si p es falsa, p → q es verdadera automáticamente (\"verdad vacía\").", "Los cuantificadores dicen sobre cuántos casos habla la afirmación: ∀ (\"para todo\") y ∃ (\"existe\"). Negarlos los intercambia: la negación de \"todas las sucursales tienen stock\" es \"existe una sucursal sin stock\" — no \"ninguna tiene stock\"."],
      example: "# Tabla de verdad de la implicación p -> q\nprint(\"p     q     p->q\")\nfor p in [True, False]:\n    for q in [True, False]:\n        implica = (not p) or q\n        print(f\"{p!s:5} {q!s:5} {implica}\")",
      quiz: [{ q: "¿Cuándo es FALSA la implicación p → q?", opts: ["Cuando p y q son falsas", "Solo cuando p es verdadera y q es falsa", "Siempre que q es falsa", "Nunca"], correct: 1 }, { q: "La negación de \"todas las cajas están selladas\" es:", opts: ["Ninguna caja está sellada", "Existe al menos una caja sin sellar", "Todas las cajas están sin sellar", "No se puede negar"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función implica(p, q) que devuelva el valor de verdad de p → q (recordá: equivale a (not p) or q).",
        starter: "def implica(p, q):\n    # tu código acá\n    pass",
        tests: "assert implica(True, True) == True, \"V -> V es V\"\nassert implica(True, False) == False, \"V -> F es F (el único caso falso)\"\nassert implica(False, True) == True, \"F -> V es V\"\nassert implica(False, False) == True, \"F -> F es V (verdad vacía)\"\nprint(\"TESTS_OK\")",
      },
    },
    M03: {
      code: "M03",
      materia: "Matemática Discreta",
      title: "Contradicción y contrapositiva",
      fuente: "MIT 6.042J — Lec 1: Introduction and proofs | Libro LLM cap. 1",
      theory: ["Demostración por contradicción: suponés que la proposición es falsa y derivás un absurdo; entonces tenía que ser verdadera. Es la técnica de la demostración clásica de que √2 es irracional, vista en la primera clase de MIT.", "La contrapositiva de p → q es (no q) → (no p), y es lógicamente EQUIVALENTE a la original — demostrar una es demostrar la otra. Ojo: no confundir con la recíproca q → p, que NO es equivalente."],
      example: "# La contrapositiva tiene exactamente la misma tabla de verdad\ndef implica(p, q):\n    return (not p) or q\n\nprint(\"p     q     p->q  (~q)->(~p)\")\nfor p in [True, False]:\n    for q in [True, False]:\n        original = implica(p, q)\n        contra = implica(not q, not p)\n        print(f\"{p!s:5} {q!s:5} {original!s:5} {contra}\")",
      quiz: [{ q: "La contrapositiva de \"si llueve, el depósito se moja\" es:", opts: ["Si el depósito se moja, llueve", "Si el depósito NO se moja, NO llueve", "Si no llueve, el depósito no se moja", "El depósito siempre se moja"], correct: 1 }, { q: "En una demostración por contradicción, se empieza:", opts: ["Probando muchos casos", "Suponiendo que la proposición es falsa", "Suponiendo que es verdadera", "Con la contrapositiva"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función contrapositiva(p, q) que devuelva el valor de verdad de (not q) → (not p). Los tests verifican que coincide con implica(p, q) en los 4 casos.",
        starter: "def contrapositiva(p, q):\n    # tu código acá (podés definir implica adentro o repetir la fórmula)\n    pass",
        tests: "for p in [True, False]:\n    for q in [True, False]:\n        assert contrapositiva(p, q) == ((not p) or q), f\"Difiere de p->q en p={p}, q={q}\"\nprint(\"TESTS_OK\")",
      },
    },
    M04: {
      code: "M04",
      materia: "Matemática Discreta",
      title: "Inducción",
      fuente: "MIT 6.042J — Lec 2: Induction | Libro LLM cap. 5",
      theory: ["La inducción demuestra que algo vale para TODOS los naturales con dos pasos: el caso base (vale para n = 0 o 1) y el paso inductivo (si vale para n, vale para n+1). Es como una fila de fichas de dominó: tirás la primera y garantizás que cada una voltea a la siguiente.", "El ejemplo canónico de la clase 2 de MIT: 1 + 2 + ... + n = n(n+1)/2. El paso inductivo suma (n+1) a ambos lados de la hipótesis y verifica que la fórmula se mantiene."],
      example: "# La fórmula de Gauss coincide con la suma explícita, caso por caso\nfor n in [1, 5, 10, 100]:\n    suma_explicita = sum(range(1, n + 1))\n    formula = n * (n + 1) // 2\n    print(f\"n={n}: suma={suma_explicita}, formula={formula}, coinciden: {suma_explicita == formula}\")",
      quiz: [{ q: "¿Cuáles son los dos pasos de una demostración por inducción?", opts: ["Hipótesis y tesis", "Caso base y paso inductivo", "Contradicción y contrapositiva", "Probar n=0 y n=1000"], correct: 1 }, { q: "En el paso inductivo se demuestra que:", opts: ["La proposición vale para n=0", "Si vale para n, entonces vale para n+1", "Vale para todos los n a la vez", "Existe un n donde vale"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función suma_gauss(n) que devuelva 1 + 2 + ... + n usando la fórmula cerrada n(n+1)/2 (con división entera, sin loops).",
        starter: "def suma_gauss(n):\n    # tu código acá\n    pass",
        tests: "assert suma_gauss(1) == 1, \"Caso base\"\nassert suma_gauss(10) == 55, \"Fallo con 10\"\nassert suma_gauss(100) == 5050, \"Fallo con 100 (el clásico de Gauss)\"\nprint(\"TESTS_OK\")",
      },
    },
    M05: {
      code: "M05",
      materia: "Matemática Discreta",
      title: "Inducción fuerte",
      fuente: "MIT 6.042J — Lec 3: Strong induction | Libro LLM cap. 5",
      theory: ["La inducción fuerte cambia la hipótesis: en vez de asumir que la proposición vale solo para n, asumís que vale para TODOS los valores anteriores (desde el caso base hasta n) para probar n+1. Sirve cuando el paso n+1 depende de casos más chicos que el inmediato anterior.", "El ejemplo de la clase 3 de MIT: con estampillas de 3 y 5 centavos se puede formar cualquier franqueo desde 8 en adelante. Para armar n+1 restás una estampilla y usás la hipótesis sobre un caso anterior — necesitás varios casos base (8, 9, 10)."],
      example: "# Todo franqueo >= 8 se arma con estampillas de 3 y 5\ndef armar_franqueo(n):\n    for a in range(n // 3 + 1):\n        if (n - 3 * a) % 5 == 0:\n            return (a, (n - 3 * a) // 5)\n    return None\n\nfor n in [8, 9, 10, 11, 17]:\n    a, b = armar_franqueo(n)\n    print(f\"{n} = 3x{a} + 5x{b}\")",
      quiz: [{ q: "La inducción fuerte asume que la proposición vale para:", opts: ["Solo n", "Todos los valores desde el caso base hasta n", "n+1", "Algún n"], correct: 1 }, { q: "En el problema de las estampillas de 3 y 5, ¿por qué hacen falta varios casos base?", opts: ["Por elegancia", "Porque el paso inductivo retrocede 3, no 1", "Porque 8 es par", "No hacen falta"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función franqueo(n) que, para n >= 8, devuelva una tupla (a, b) con cantidades de estampillas de 3 y 5 tales que 3a + 5b = n. Cualquier solución válida sirve.",
        starter: "def franqueo(n):\n    # tu código acá\n    pass",
        tests: "for n in [8, 9, 10, 23, 100]:\n    a, b = franqueo(n)\n    assert a >= 0 and b >= 0 and 3*a + 5*b == n, f\"Solución inválida para {n}\"\nprint(\"TESTS_OK\")",
      },
    },
    M06: {
      code: "M06",
      materia: "Matemática Discreta",
      title: "Conjuntos y funciones",
      fuente: "MIT 6.042J — Libro LLM cap. 4 (Mathematical Data Types; sin clase propia en F2010)",
      theory: ["Un conjunto es una colección sin orden ni repetidos. Las operaciones básicas: unión (todo lo que está en alguno), intersección (lo que está en ambos), diferencia (lo de uno que no está en el otro). Dos conjuntos son disjuntos si su intersección es vacía.", "Una función asigna a cada elemento del dominio exactamente un elemento del codominio. En Python, los sets y dicts son la traducción directa de estas ideas — por eso este tema ya te sonaba de PRG1 (L13): acá le ponemos el formalismo."],
      example: "# Operaciones de conjuntos con proveedores de dos sucursales\nprov_norte = {\"Coca\", \"Arcor\", \"Quilmes\"}\nprov_sur = {\"Arcor\", \"Bimbo\"}\n\nprint(\"Unión:\", prov_norte | prov_sur)\nprint(\"Intersección:\", prov_norte & prov_sur)\nprint(\"Solo Norte:\", prov_norte - prov_sur)\nprint(\"Disjuntos:\", prov_norte.isdisjoint(prov_sur))",
      quiz: [{ q: "Dos conjuntos son disjuntos cuando:", opts: ["Tienen el mismo tamaño", "Su intersección es vacía", "Su unión es vacía", "Uno contiene al otro"], correct: 1 }, { q: "Una función asigna a cada elemento del dominio:", opts: ["Cero o más valores", "Exactamente un valor", "Al menos dos valores", "Un valor solo si existe"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función proveedores_compartidos(suc_a, suc_b) que reciba dos listas de proveedores (pueden tener repetidos) y devuelva un set con los proveedores que están en ambas.",
        starter: "def proveedores_compartidos(suc_a, suc_b):\n    # tu código acá\n    pass",
        tests: "assert proveedores_compartidos([\"Coca\", \"Arcor\", \"Coca\"], [\"Arcor\", \"Bimbo\"]) == {\"Arcor\"}, \"Fallo caso 1\"\nassert proveedores_compartidos([\"Coca\"], [\"Bimbo\"]) == set(), \"Fallo con disjuntos\"\nprint(\"TESTS_OK\")",
      },
    },
    M07: {
      code: "M07",
      materia: "Matemática Discreta",
      title: "Relaciones y órdenes parciales",
      fuente: "MIT 6.042J — Lec 11: Relations, partial orders, and scheduling | Libro LLM cap. 9",
      theory: ["Una relación sobre un conjunto es un conjunto de pares (a, b): \"a depende de b\", \"a es prerrequisito de b\". Tres propiedades clave: reflexiva (todo elemento se relaciona consigo mismo), simétrica (si a~b entonces b~a) y transitiva (si a~b y b~c, entonces a~c).", "Un orden parcial es una relación reflexiva, antisimétrica y transitiva — como los prerrequisitos entre materias de esta carrera. \"Parcial\" porque puede haber elementos incomparables: MDIS y ALG no dependen una de otra, se pueden cursar en paralelo. Es exactamente el tema de scheduling de la Lec 11 de MIT."],
      example: "# Chequear si una relación es reflexiva sobre un conjunto de tareas\ntareas = {\"comprar\", \"recibir\", \"vender\"}\nrelacion = {(\"comprar\", \"comprar\"), (\"recibir\", \"recibir\"),\n            (\"vender\", \"vender\"), (\"comprar\", \"recibir\")}\n\nreflexiva = all((t, t) in relacion for t in tareas)\nprint(\"¿Reflexiva?:\", reflexiva)",
      quiz: [{ q: "Una relación es transitiva si:", opts: ["a~a para todo a", "a~b implica b~a", "a~b y b~c implican a~c", "No tiene pares repetidos"], correct: 2 }, { q: "En un orden parcial, dos elementos incomparables significan que:", opts: ["Hay un error en la relación", "Ninguno precede al otro (pueden ir en paralelo)", "Son iguales", "La relación no es reflexiva"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función es_reflexiva(elementos, relacion) que reciba un set de elementos y un set de pares (tuplas) y devuelva True si todo elemento se relaciona consigo mismo.",
        starter: "def es_reflexiva(elementos, relacion):\n    # tu código acá\n    pass",
        tests: "assert es_reflexiva({\"a\", \"b\"}, {(\"a\",\"a\"), (\"b\",\"b\"), (\"a\",\"b\")}) == True, \"Fallo caso reflexivo\"\nassert es_reflexiva({\"a\", \"b\"}, {(\"a\",\"a\"), (\"a\",\"b\")}) == False, \"Falta (b,b)\"\nprint(\"TESTS_OK\")",
      },
    },
    M08: {
      code: "M08",
      materia: "Matemática Discreta",
      title: "Divisibilidad y MCD: el algoritmo de Euclides",
      fuente: "MIT 6.042J — Lec 4: Number theory I | Libro LLM cap. 8",
      theory: ["a divide a b si b = k·a para algún entero k. El máximo común divisor (MCD) de a y b es el mayor entero que divide a ambos. La clase 4 de MIT lo presenta con el problema de los bidones de agua de Duro de Matar 3: con bidones de 3 y 5 galones solo podés medir múltiplos de mcd(3,5) = 1.", "El algoritmo de Euclides calcula el MCD con una idea de hace 2300 años: mcd(a, b) = mcd(b, a mod b), repitiendo hasta que el resto sea 0. Es rapidísimo incluso con números enormes — por eso sigue siendo la base de la criptografía moderna."],
      example: "# Euclides paso a paso\na, b = 1071, 462\nwhile b != 0:\n    print(f\"mcd({a}, {b})\")\n    a, b = b, a % b\nprint(f\"MCD = {a}\")",
      quiz: [{ q: "El paso central del algoritmo de Euclides es:", opts: ["mcd(a,b) = mcd(a-1, b)", "mcd(a,b) = mcd(b, a mod b)", "mcd(a,b) = a*b", "Probar todos los divisores"], correct: 1 }, { q: "¿Cuándo termina el algoritmo de Euclides?", opts: ["Cuando a == b", "Cuando el resto es 0", "Después de a pasos", "Cuando a es primo"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función mcd(a, b) que calcule el máximo común divisor con el algoritmo de Euclides.",
        starter: "def mcd(a, b):\n    # tu código acá\n    pass",
        tests: "assert mcd(1071, 462) == 21, \"El ejemplo clásico de Euclides\"\nassert mcd(3, 5) == 1, \"Los bidones de Duro de Matar 3\"\nassert mcd(12, 0) == 12, \"mcd con 0\"\nprint(\"TESTS_OK\")",
      },
    },
    M09: {
      code: "M09",
      materia: "Matemática Discreta",
      title: "Aritmética modular y congruencias",
      fuente: "MIT 6.042J — Lec 5: Number theory II | Libro LLM cap. 8",
      theory: ["a ≡ b (mod m) significa que a y b dejan el mismo resto al dividir por m — o, equivalente, que m divide a (a − b). Es la aritmética del reloj: 15 hs ≡ 3 (mod 12). Suma y producto se llevan bien con el módulo: podés reducir antes o después y da lo mismo.", "La clase 5 de MIT usa esto para criptografía: los sistemas tipo RSA funcionan porque operar módulo m es fácil, pero deshacerlo sin la clave es computacionalmente durísimo. Vos ya usás congruencias sin saberlo: el dígito verificador de un código de barras es una cuenta módulo 10."],
      example: "# La aritmética del reloj y la propiedad clave del módulo\nprint(\"15 horas en reloj de 12:\", 15 % 12)\na, b, m = 47, 23, 12\nprint(\"(a+b) % m =\", (a + b) % m)\nprint(\"((a%m)+(b%m)) % m =\", ((a % m) + (b % m)) % m)  # da lo mismo",
      quiz: [{ q: "a ≡ b (mod m) significa que:", opts: ["a == b", "a y b dejan el mismo resto al dividir por m", "a divide a b", "a y b son primos"], correct: 1 }, { q: "¿Cuánto es 17 ≡ ? (mod 5)?", opts: ["0", "1", "2", "3"], correct: 2 }],
      exercise: {
        prompt: "Escribí una función son_congruentes(a, b, m) que devuelva True si a ≡ b (mod m).",
        starter: "def son_congruentes(a, b, m):\n    # tu código acá\n    pass",
        tests: "assert son_congruentes(15, 3, 12) == True, \"15 y 3 en reloj de 12\"\nassert son_congruentes(17, 2, 5) == True, \"17 mod 5 = 2\"\nassert son_congruentes(10, 3, 4) == False, \"10 mod 4 = 2, no 3\"\nprint(\"TESTS_OK\")",
      },
    },
    M10: {
      code: "M10",
      materia: "Matemática Discreta",
      title: "Grafos: definiciones y coloreo",
      fuente: "MIT 6.042J — Lec 6: Graph theory and coloring | Libro LLM cap. 11",
      theory: ["Un grafo son vértices (puntos) y aristas (conexiones entre pares). El grado de un vértice es cuántas aristas lo tocan. En código, la representación más práctica es un diccionario de adyacencia: cada vértice mapea a la lista de sus vecinos — mirá cómo conecta con los dicts de PRG1.", "La clase 6 de MIT presenta el coloreo: asignar colores a los vértices de modo que vecinos tengan colores distintos. Su aplicación original es armar horarios de exámenes sin choques — el mismo problema que asignar turnos a empleados que no pueden solaparse."],
      example: "# Sucursales conectadas por rutas de reparto (dict de adyacencia)\ngrafo = {\n    \"Norte\": [\"Sur\", \"Oeste\"],\n    \"Sur\": [\"Norte\", \"Oeste\"],\n    \"Oeste\": [\"Norte\", \"Sur\"],\n    \"Este\": [],\n}\nfor v, vecinos in grafo.items():\n    print(f\"{v}: grado {len(vecinos)}\")",
      quiz: [{ q: "El grado de un vértice es:", opts: ["Su color", "La cantidad de aristas que lo tocan", "Su posición en el dibujo", "La cantidad total de vértices"], correct: 1 }, { q: "En un coloreo válido, dos vértices vecinos:", opts: ["Tienen el mismo color", "Tienen colores distintos", "No tienen color", "Son del mismo grado"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función grado(grafo, v) que reciba un dict de adyacencia y un vértice, y devuelva su grado (cantidad de vecinos).",
        starter: "def grado(grafo, v):\n    # tu código acá\n    pass",
        tests: "g = {\"a\": [\"b\", \"c\"], \"b\": [\"a\"], \"c\": [\"a\"], \"d\": []}\nassert grado(g, \"a\") == 2, \"a tiene 2 vecinos\"\nassert grado(g, \"d\") == 0, \"d está aislado\"\nprint(\"TESTS_OK\")",
      },
    },
    M11: {
      code: "M11",
      materia: "Matemática Discreta",
      title: "Matching y grafos bipartitos",
      fuente: "MIT 6.042J — Lec 7: Matching problems | Libro LLM cap. 11",
      theory: ["Un matching es un conjunto de aristas sin vértices en común: cada elemento queda emparejado con a lo sumo uno del otro lado. La clase 7 de MIT lo presenta como el problema de emparejar de forma estable — la misma matemática que asignar repartidores a rutas: cada repartidor una ruta, cada ruta un repartidor.", "Un grafo bipartito tiene sus vértices partidos en dos grupos y todas las aristas cruzan de un grupo al otro (repartidores ↔ rutas). El matching perfecto empareja a todos; el teorema de Hall dice exactamente cuándo es posible."],
      example: "# ¿Esta asignación repartidor->ruta es un matching válido?\nasignacion = [(\"Marcos\", \"Ruta1\"), (\"Ana\", \"Ruta2\"), (\"Luis\", \"Ruta3\")]\nizquierda = [a for a, _ in asignacion]\nderecha = [b for _, b in asignacion]\nvalido = len(set(izquierda)) == len(izquierda) and len(set(derecha)) == len(derecha)\nprint(\"Matching válido:\", valido)",
      quiz: [{ q: "En un matching, dos aristas distintas:", opts: ["Comparten exactamente un vértice", "No comparten ningún vértice", "Comparten los dos vértices", "Deben cruzarse"], correct: 1 }, { q: "Un grafo bipartito es aquel donde:", opts: ["Todos los vértices tienen grado 2", "Los vértices se parten en dos grupos y las aristas cruzan entre ellos", "Hay exactamente dos aristas", "No hay ciclos"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función es_matching(pares) que reciba una lista de tuplas (izq, der) y devuelva True si ningún elemento (de ningún lado) aparece más de una vez.",
        starter: "def es_matching(pares):\n    # tu código acá\n    pass",
        tests: "assert es_matching([(\"Marcos\",\"R1\"), (\"Ana\",\"R2\")]) == True, \"Matching válido\"\nassert es_matching([(\"Marcos\",\"R1\"), (\"Marcos\",\"R2\")]) == False, \"Marcos repetido\"\nassert es_matching([(\"Marcos\",\"R1\"), (\"Ana\",\"R1\")]) == False, \"Ruta R1 repetida\"\nprint(\"TESTS_OK\")",
      },
    },
    M12: {
      code: "M12",
      materia: "Matemática Discreta",
      title: "Árboles y árbol de expansión mínima",
      fuente: "MIT 6.042J — Lec 8: Graph theory II: minimum spanning trees | Libro LLM cap. 11",
      theory: ["Un árbol es un grafo conexo sin ciclos, y siempre cumple: n vértices, n−1 aristas. Un árbol de expansión de un grafo conexo es un subconjunto de aristas que conecta todos los vértices sin formar ciclos — la red mínima que mantiene todo comunicado.", "Si las aristas tienen peso (costo de cada tramo de ruta), el árbol de expansión MÍNIMA (MST) es el de peso total más chico: la forma más barata de conectar todas las sucursales. La clase 8 de MIT demuestra que el enfoque goloso — elegir siempre la arista más barata que no arme ciclo — encuentra el óptimo."],
      example: "# Dos formas de conectar 4 sucursales: comparar el costo total\nopcion_a = [(\"N\",\"S\",10), (\"S\",\"O\",5), (\"O\",\"E\",8)]\nopcion_b = [(\"N\",\"S\",10), (\"N\",\"O\",12), (\"N\",\"E\",15)]\nfor nombre, aristas in [(\"A\", opcion_a), (\"B\", opcion_b)]:\n    total = sum(peso for _, _, peso in aristas)\n    print(f\"Opción {nombre}: costo total {total}\")",
      quiz: [{ q: "Un árbol con n vértices tiene exactamente:", opts: ["n aristas", "n-1 aristas", "n+1 aristas", "2n aristas"], correct: 1 }, { q: "El árbol de expansión mínima de un grafo con pesos es:", opts: ["El camino más corto entre dos vértices", "El subconjunto de aristas más barato que conecta todo sin ciclos", "El grafo completo", "El árbol con más aristas"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función costo_total(aristas) que reciba una lista de tuplas (origen, destino, peso) y devuelva la suma de los pesos.",
        starter: "def costo_total(aristas):\n    # tu código acá\n    pass",
        tests: "assert costo_total([(\"N\",\"S\",10), (\"S\",\"O\",5)]) == 15, \"Fallo caso 1\"\nassert costo_total([]) == 0, \"Sin aristas, costo 0\"\nprint(\"TESTS_OK\")",
      },
    },
    M13: {
      code: "M13",
      materia: "Matemática Discreta",
      title: "Conectividad y recorridos",
      fuente: "MIT 6.042J — Lec 9: Communication networks + Lec 10: Graph theory III | Libro LLM cap. 11",
      theory: ["Un camino es una secuencia de vértices donde cada uno es vecino del siguiente; un grafo es conexo si hay camino entre cualquier par. Las clases 9 y 10 de MIT estudian redes de comunicación con exactamente esta pregunta: ¿si se cae un enlace, sigue todo conectado?", "Para responder \"¿hay camino de A a B?\" en código, el recorrido estándar es: arrancás en A, visitás sus vecinos, después los vecinos de los vecinos, marcando visitados para no ciclar. Es la base de BFS/DFS que vas a formalizar en ALGO — acá te alcanza con la versión con una lista pendientes y un set de visitados."],
      example: "# ¿Llega la mercadería de Norte a Este por la red de rutas?\ngrafo = {\"Norte\": [\"Sur\"], \"Sur\": [\"Norte\", \"Oeste\"],\n         \"Oeste\": [\"Sur\", \"Este\"], \"Este\": [\"Oeste\"]}\n\npendientes, visitados = [\"Norte\"], set()\nwhile pendientes:\n    actual = pendientes.pop()\n    if actual in visitados:\n        continue\n    visitados.add(actual)\n    pendientes.extend(grafo[actual])\nprint(\"Alcanzables desde Norte:\", sorted(visitados))",
      quiz: [{ q: "Un grafo es conexo si:", opts: ["Todos los vértices tienen el mismo grado", "Hay camino entre cualquier par de vértices", "No tiene ciclos", "Tiene una sola arista"], correct: 1 }, { q: "Al recorrer un grafo, ¿para qué sirve el set de visitados?", opts: ["Para ordenar los vértices", "Para no visitar el mismo vértice dos veces (y no ciclar)", "Para contar aristas", "No sirve para nada"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función hay_camino(grafo, origen, destino) que devuelva True si existe un camino entre origen y destino en el dict de adyacencia (usá el patrón pendientes + visitados del ejemplo).",
        starter: "def hay_camino(grafo, origen, destino):\n    # tu código acá\n    pass",
        tests: "g = {\"a\": [\"b\"], \"b\": [\"a\", \"c\"], \"c\": [\"b\"], \"d\": []}\nassert hay_camino(g, \"a\", \"c\") == True, \"a llega a c vía b\"\nassert hay_camino(g, \"a\", \"d\") == False, \"d está aislado\"\nassert hay_camino(g, \"a\", \"a\") == True, \"Un vértice se alcanza a sí mismo\"\nprint(\"TESTS_OK\")",
      },
    },
    M14: {
      code: "M14",
      materia: "Matemática Discreta",
      title: "Sumas y series",
      fuente: "MIT 6.042J — Lec 12: Sums | Libro LLM cap. 13",
      theory: ["Muchos análisis terminan en una suma: total de operaciones, total de intereses, total acumulado. Las dos que resuelven casi todo: la aritmética (1+2+...+n = n(n+1)/2, ya la demostraste por inducción en M04) y la geométrica (1 + x + x² + ... + xⁿ = (x^(n+1) − 1)/(x − 1) para x ≠ 1).", "La geométrica aparece cada vez que algo crece o decrece a ritmo constante — la clase 12 de MIT la usa para calcular el valor de una anualidad: cuánto valen hoy pagos futuros con inflación. Un tema que en Argentina no hace falta explicar."],
      example: "# Suma geométrica: forma explícita vs. fórmula cerrada\nx, n = 2, 10\nexplicita = sum(x**k for k in range(n + 1))\nformula = (x**(n + 1) - 1) // (x - 1)\nprint(f\"Suma de potencias de {x} hasta {n}: {explicita}\")\nprint(f\"Fórmula cerrada: {formula}, coinciden: {explicita == formula}\")",
      quiz: [{ q: "La suma 1 + x + x² + ... + xⁿ (x ≠ 1) tiene fórmula cerrada:", opts: ["n(n+1)/2", "(x^(n+1) − 1)/(x − 1)", "xⁿ", "n·x"], correct: 1 }, { q: "¿Cuánto vale 1 + 2 + 4 + 8 + 16?", opts: ["30", "31", "32", "producto de todos"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función suma_geometrica(x, n) que devuelva 1 + x + x² + ... + xⁿ para x entero ≥ 2 (usá la fórmula cerrada con división entera).",
        starter: "def suma_geometrica(x, n):\n    # tu código acá\n    pass",
        tests: "assert suma_geometrica(2, 4) == 31, \"1+2+4+8+16 = 31\"\nassert suma_geometrica(3, 3) == 40, \"1+3+9+27 = 40\"\nassert suma_geometrica(2, 0) == 1, \"Solo el término 1\"\nprint(\"TESTS_OK\")",
      },
    },
    M15: {
      code: "M15",
      materia: "Matemática Discreta",
      title: "Asintótica y notación O",
      fuente: "MIT 6.042J — Lec 13: Sums and asymptotics | Libro LLM cap. 13",
      theory: ["La notación O compara cómo crecen las funciones cuando n se hace grande, ignorando constantes y términos menores: 3n² + 50n + 7 es O(n²), porque para n grande el n² domina todo. Es el lenguaje con el que vas a medir algoritmos en PRG2 y ALGO.", "La jerarquía que hay que tener tatuada, de más lento a más rápido crecimiento: constante < log n < n < n log n < n² < 2ⁿ. Un algoritmo O(2ⁿ) es inservible ya con n = 60; uno O(n log n) procesa millones sin despeinarse."],
      example: "# Ver la jerarquía de crecimiento con números concretos\nimport math\nfor n in [10, 100, 1000]:\n    print(f\"n={n}: log={math.log2(n):.0f}, n={n}, nlogn={n*math.log2(n):.0f}, n2={n**2}\")",
      quiz: [{ q: "3n² + 50n + 7 es:", opts: ["O(n)", "O(n²)", "O(n³)", "O(50n)"], correct: 1 }, { q: "Ordenados de crecimiento más lento a más rápido:", opts: ["n², n log n, n", "n, n log n, n²", "n log n, n, n²", "n², n, log n"], correct: 1 }],
      exercise: {
        prompt: "Un algoritmo con dos loops anidados sobre n elementos hace n² comparaciones, más n operaciones de preparación. Escribí operaciones(n) que devuelva el total exacto (n² + n).",
        starter: "def operaciones(n):\n    # tu código acá\n    pass",
        tests: "assert operaciones(10) == 110, \"100 + 10\"\nassert operaciones(100) == 10100, \"Con n=100 el n2 ya domina: 10000 vs 100\"\nassert operaciones(1) == 2, \"Caso mínimo\"\nprint(\"TESTS_OK\")",
      },
    },
    M16: {
      code: "M16",
      materia: "Matemática Discreta",
      title: "Recurrencias",
      fuente: "MIT 6.042J — Lec 14: Divide and conquer recurrences + Lec 15: Linear recurrences",
      theory: ["Una recurrencia define una cantidad en función de casos más chicos: T(n) = 2·T(n−1) + 1. Es la contracara matemática de la recursión en código, y el modo natural de medir cuánto cuesta un algoritmo que se llama a sí mismo.", "El ejemplo con el que abre la clase 14 de MIT: las Torres de Hanoi. Mover n discos exige mover n−1, mover el grande, y mover n−1 de nuevo: T(n) = 2T(n−1) + 1, cuya solución cerrada es 2ⁿ − 1. Con 64 discos, más pasos que segundos tiene la edad del universo — las recurrencias te dicen eso antes de ejecutar nada."],
      example: "# Torres de Hanoi: la recurrencia y su fórmula cerrada coinciden\ndef hanoi(n):\n    if n == 0:\n        return 0\n    return 2 * hanoi(n - 1) + 1\n\nfor n in [1, 3, 5, 10]:\n    print(f\"T({n}) = {hanoi(n)}, fórmula 2^n - 1 = {2**n - 1}\")",
      quiz: [{ q: "La recurrencia de Hanoi T(n) = 2T(n−1) + 1 tiene solución cerrada:", opts: ["n²", "2ⁿ − 1", "2n + 1", "n!"], correct: 1 }, { q: "Una recurrencia define una cantidad:", opts: ["Con un valor fijo", "En función de casos más chicos de sí misma", "Solo con sumas", "Sin caso base"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función movimientos_hanoi(n) que calcule los movimientos mínimos para n discos usando la recurrencia T(n) = 2·T(n−1) + 1 con T(0) = 0 (recursiva o con loop).",
        starter: "def movimientos_hanoi(n):\n    # tu código acá\n    pass",
        tests: "assert movimientos_hanoi(0) == 0, \"Caso base\"\nassert movimientos_hanoi(3) == 7, \"3 discos, 7 movimientos\"\nassert movimientos_hanoi(10) == 1023, \"2^10 - 1\"\nprint(\"TESTS_OK\")",
      },
    },
    M17: {
      code: "M17",
      materia: "Matemática Discreta",
      title: "Conteo I: reglas básicas y permutaciones",
      fuente: "MIT 6.042J — Lec 16: Counting rules I | Libro LLM cap. 14",
      theory: ["Regla del producto: si una decisión tiene a opciones y la siguiente b, hay a·b combinaciones totales. Regla de la suma: si dos casos no se pueden dar a la vez, se suman. Con esas dos reglas se cuenta casi todo — la clase 16 de MIT las usa para contar contraseñas posibles.", "Una permutación es un ordenamiento: n elementos se ordenan de n! formas (n factorial: n·(n−1)·...·1). Si solo elegís y ordenás k de los n, son n·(n−1)·...·(n−k+1) = n!/(n−k)! formas."],
      example: "# ¿De cuántas formas se pueden ordenar 5 productos en una góndola?\nimport math\nn = 5\nprint(f\"Permutaciones de {n}: {math.factorial(n)}\")\n# ¿Y elegir y ordenar 3 de 5 en la vidriera?\nprint(\"Elegir y ordenar 3 de 5:\", math.factorial(5) // math.factorial(2))",
      quiz: [{ q: "Un menú tiene 3 entradas y 4 platos principales. ¿Cuántos menús (entrada + plato)?", opts: ["7", "12", "34", "3"], correct: 1 }, { q: "¿De cuántas formas se ordenan 4 elementos distintos?", opts: ["4", "16", "24", "8"], correct: 2 }],
      exercise: {
        prompt: "Escribí una función ordenamientos(n, k) que devuelva de cuántas formas se pueden elegir y ordenar k elementos de n, es decir n!/(n−k)! (podés usar math.factorial o un loop).",
        starter: "def ordenamientos(n, k):\n    # tu código acá\n    pass",
        tests: "assert ordenamientos(5, 5) == 120, \"5! = 120\"\nassert ordenamientos(5, 3) == 60, \"5*4*3\"\nassert ordenamientos(4, 0) == 1, \"Elegir 0: una sola forma (no elegir nada)\"\nprint(\"TESTS_OK\")",
      },
    },
    M18: {
      code: "M18",
      materia: "Matemática Discreta",
      title: "Conteo II: combinaciones, palomar e inclusión-exclusión",
      fuente: "MIT 6.042J — Lec 17: Counting rules II | Libro LLM cap. 14-15",
      theory: ["Una combinación elige k de n SIN importar el orden: C(n,k) = n!/(k!(n−k)!). La diferencia con la permutación es esa: elegir 3 productos para una promo (combinación) no es lo mismo que ordenarlos en la vidriera (permutación).", "Dos herramientas más de la clase 17: el principio del palomar (si metés más palomas que casilleros, algún casillero tiene dos — con 13 personas, seguro dos cumplen el mismo mes) e inclusión-exclusión (|A ∪ B| = |A| + |B| − |A ∩ B|: si sumás dos grupos que se solapan, restá el solapamiento para no contar doble)."],
      example: "# Combinaciones e inclusión-exclusión\nimport math\nprint(\"Elegir 3 productos de 10 para la promo:\", math.comb(10, 3))\nclientes_norte, clientes_sur, en_ambas = 120, 80, 25\nprint(\"Clientes totales (sin contar doble):\", clientes_norte + clientes_sur - en_ambas)",
      quiz: [{ q: "C(5, 2) — elegir 2 de 5 sin orden — vale:", opts: ["20", "10", "25", "7"], correct: 1 }, { q: "Con 13 personas, el principio del palomar garantiza que:", opts: ["Todas cumplen en meses distintos", "Al menos dos cumplen el mismo mes", "Alguien cumple en enero", "Nada"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función combinaciones(n, k) que devuelva C(n, k) = n!/(k!(n−k)!) usando math.factorial (sin usar math.comb).",
        starter: "import math\n\ndef combinaciones(n, k):\n    # tu código acá\n    pass",
        tests: "assert combinaciones(5, 2) == 10, \"C(5,2) = 10\"\nassert combinaciones(10, 3) == 120, \"C(10,3) = 120\"\nassert combinaciones(4, 4) == 1, \"Elegir todos: una forma\"\nprint(\"TESTS_OK\")",
      },
    },
    M19: {
      code: "M19",
      materia: "Matemática Discreta",
      title: "Probabilidad: espacios muestrales",
      fuente: "MIT 6.042J — Lec 18: Probability introduction | Libro LLM cap. 16",
      theory: ["El espacio muestral es el conjunto de todos los resultados posibles de un experimento; un evento es un subconjunto. Cuando todos los resultados son igualmente probables, P(evento) = casos favorables / casos totales. Dos dados tienen 36 resultados; \"suma 7\" tiene 6 → P = 6/36 = 1/6.", "La regla de oro de la clase 18 de MIT, ilustrada con el problema de Monty Hall: la intuición probabilística falla seguido; el método de armar el espacio muestral completo y contar, no. Ante la duda, enumerá — y en Python enumerar es un doble for."],
      example: "# Espacio muestral de dos dados: contar en vez de intuir\nfavorables = 0\nfor d1 in range(1, 7):\n    for d2 in range(1, 7):\n        if d1 + d2 == 7:\n            favorables += 1\nprint(f\"P(suma 7) = {favorables}/36\")",
      quiz: [{ q: "Con resultados equiprobables, la probabilidad de un evento es:", opts: ["Siempre 1/2", "Casos favorables sobre casos totales", "Casos totales sobre favorables", "El tamaño del espacio muestral"], correct: 1 }, { q: "El espacio muestral de tirar dos dados tiene:", opts: ["12 resultados", "36 resultados", "6 resultados", "21 resultados"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función casos_suma(objetivo) que devuelva cuántos resultados de tirar dos dados suman exactamente objetivo (enumerá con doble for).",
        starter: "def casos_suma(objetivo):\n    # tu código acá\n    pass",
        tests: "assert casos_suma(7) == 6, \"La suma más probable\"\nassert casos_suma(2) == 1, \"Solo (1,1)\"\nassert casos_suma(13) == 0, \"Imposible con dos dados\"\nprint(\"TESTS_OK\")",
      },
    },
    M20: {
      code: "M20",
      materia: "Matemática Discreta",
      title: "Probabilidad condicional y Bayes",
      fuente: "MIT 6.042J — Lec 19: Conditional probability | Libro LLM cap. 17",
      theory: ["P(A|B) es la probabilidad de A sabiendo que B ocurrió: restringís el espacio muestral a B. La fórmula: P(A|B) = P(A y B) / P(B). El teorema de Bayes la da vuelta: P(A|B) = P(B|A)·P(A) / P(B) — te deja pasar de \"probabilidad del síntoma dada la causa\" a \"probabilidad de la causa dado el síntoma\".", "La clase 19 de MIT lo aplica al clásico del test médico: si una condición afecta al 1% y el test acierta el 90%, un positivo NO significa 90% de tener la condición — los falsos positivos del 99% sano pesan muchísimo. Es el mismo cálculo detrás de un detector de anomalías de stock: pocas alertas verdaderas entre muchas falsas."],
      example: "# Bayes con el clásico del test: contando sobre 10000 casos\npoblacion = 10000\nenfermos = int(poblacion * 0.01)          # 1% tiene la condición\nsanos = poblacion - enfermos\npositivos_verdaderos = int(enfermos * 0.90)   # sensibilidad 90%\nfalsos_positivos = int(sanos * 0.10)          # 10% de falsos positivos\ntotal_positivos = positivos_verdaderos + falsos_positivos\nprint(f\"P(enfermo | positivo) = {positivos_verdaderos}/{total_positivos}\"\n      f\" = {positivos_verdaderos/total_positivos:.2%}\")",
      quiz: [{ q: "P(A|B) se calcula como:", opts: ["P(A) · P(B)", "P(A y B) / P(B)", "P(A) + P(B)", "P(B) / P(A)"], correct: 1 }, { q: "En el ejemplo del test (1% de prevalencia, 90% de acierto), un positivo implica probabilidad de estar enfermo:", opts: ["Del 90%", "Mucho menor al 90%, por los falsos positivos", "Del 100%", "Del 1%"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función prob_condicional(casos_ab, casos_b) que devuelva P(A|B) = casos_ab / casos_b redondeada a 4 decimales.",
        starter: "def prob_condicional(casos_ab, casos_b):\n    # tu código acá\n    pass",
        tests: "assert prob_condicional(90, 1080) == 0.0833, \"El caso del test médico\"\nassert prob_condicional(6, 36) == 0.1667, \"Suma 7 en dos dados\"\nassert prob_condicional(0, 10) == 0.0, \"Evento imposible\"\nprint(\"TESTS_OK\")",
      },
    },
    M21: {
      code: "M21",
      materia: "Matemática Discreta",
      title: "Independencia",
      fuente: "MIT 6.042J — Lec 20: Independence | Libro LLM cap. 18",
      theory: ["Dos eventos son independientes si saber que uno ocurrió no cambia la probabilidad del otro: P(A y B) = P(A)·P(B). Dos tiradas de dado son independientes; \"llueve\" y \"caen las ventas del delivery\" seguramente no.", "La advertencia de la clase 20 de MIT: asumir independencia sin justificarla es de los errores más caros del razonamiento probabilístico — su ejemplo son fallas judiciales reales por multiplicar probabilidades de eventos que no eran independientes. Antes de multiplicar, preguntate si un evento informa sobre el otro."],
      example: "# Verificar independencia con el espacio muestral de dos dados\ntotal = 36\np_d1_par = 18 / total          # primer dado par\np_suma_7 = 6 / total           # suma 7\ncasos_ambos = sum(1 for d1 in range(1,7) for d2 in range(1,7)\n                  if d1 % 2 == 0 and d1 + d2 == 7)\np_ambos = casos_ambos / total\nprint(f\"P(A)·P(B) = {p_d1_par * p_suma_7:.4f}\")\nprint(f\"P(A y B) = {p_ambos:.4f}\")\nprint(\"Independientes:\", abs(p_ambos - p_d1_par * p_suma_7) < 1e-9)",
      quiz: [{ q: "A y B son independientes cuando:", opts: ["P(A y B) = P(A) + P(B)", "P(A y B) = P(A) · P(B)", "P(A) = P(B)", "No pueden ocurrir juntos"], correct: 1 }, { q: "¿Se puede asumir independencia entre dos eventos cualesquiera?", opts: ["Sí, siempre", "No: hay que justificar que uno no informa sobre el otro", "Solo si son del mismo experimento", "Solo con dados"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función son_independientes(p_a, p_b, p_ab) que devuelva True si p_ab es igual a p_a·p_b con tolerancia de 1e-9 (comparación de floats).",
        starter: "def son_independientes(p_a, p_b, p_ab):\n    # tu código acá\n    pass",
        tests: "assert son_independientes(0.5, 1/6, 1/12) == True, \"Dado par y suma 7\"\nassert son_independientes(0.5, 0.5, 0.4) == False, \"0.4 != 0.25\"\nprint(\"TESTS_OK\")",
      },
    },
    M22: {
      code: "M22",
      materia: "Matemática Discreta",
      title: "Variables aleatorias",
      fuente: "MIT 6.042J — Lec 21: Random variables | Libro LLM cap. 19",
      theory: ["Una variable aleatoria asigna un número a cada resultado del experimento: \"la suma de los dos dados\", \"las unidades vendidas hoy\". Su distribución dice con qué probabilidad toma cada valor — en Python, un dict {valor: probabilidad} que debe sumar 1.", "Sobre una variable aleatoria podés preguntar por eventos: P(ventas ≥ 10) es la suma de las probabilidades de todos los valores que cumplen la condición. Ese pasaje de \"resultados\" a \"números con distribución\" es lo que permite calcular esperanzas en la próxima lección."],
      example: "# Distribución de la demanda diaria de un producto\ndemanda = {0: 0.1, 1: 0.2, 2: 0.4, 3: 0.2, 4: 0.1}\nprint(\"Suma de probabilidades:\", sum(demanda.values()))\np_al_menos_2 = sum(p for valor, p in demanda.items() if valor >= 2)\nprint(f\"P(demanda >= 2) = {p_al_menos_2:.1f}\")",
      quiz: [{ q: "Una variable aleatoria es:", opts: ["Un número al azar sin regla", "Una función que asigna un número a cada resultado del experimento", "Siempre un dado", "Un evento"], correct: 1 }, { q: "Las probabilidades de una distribución deben sumar:", opts: ["0", "1", "100", "Depende del experimento"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función prob_al_menos(dist, umbral) que reciba un dict {valor: prob} y devuelva P(X ≥ umbral) redondeada a 4 decimales.",
        starter: "def prob_al_menos(dist, umbral):\n    # tu código acá\n    pass",
        tests: "d = {0: 0.1, 1: 0.2, 2: 0.4, 3: 0.2, 4: 0.1}\nassert prob_al_menos(d, 2) == 0.7, \"0.4+0.2+0.1\"\nassert prob_al_menos(d, 0) == 1.0, \"Todos los valores\"\nassert prob_al_menos(d, 5) == 0.0, \"Ningún valor llega\"\nprint(\"TESTS_OK\")",
      },
    },
    M23: {
      code: "M23",
      materia: "Matemática Discreta",
      title: "Esperanza",
      fuente: "MIT 6.042J — Lec 22: Expectation I + Lec 23: Expectation II | Libro LLM cap. 19",
      theory: ["La esperanza E[X] es el promedio ponderado por probabilidad: E[X] = Σ valor·probabilidad. Es \"el promedio a la larga\": si la demanda diaria tiene esperanza 2.0, en 30 días esperás vender unas 60 unidades — el número que necesitás para decidir cuánto stock reponer.", "La propiedad estrella de las clases 22-23 de MIT: la linealidad. E[X + Y] = E[X] + E[Y] SIEMPRE, sean o no independientes las variables. Eso permite partir un problema enorme (demanda total de 3 sucursales) en pedazos simples y sumar las esperanzas."],
      example: "# Esperanza de la demanda diaria + linealidad entre sucursales\ndemanda_norte = {0: 0.1, 1: 0.2, 2: 0.4, 3: 0.2, 4: 0.1}\ne_norte = sum(v * p for v, p in demanda_norte.items())\nprint(f\"E[demanda Norte] = {e_norte}\")\ne_sur = 1.5\nprint(f\"E[demanda total] = E[Norte] + E[Sur] = {e_norte + e_sur}\")",
      quiz: [{ q: "La esperanza de una variable aleatoria es:", opts: ["Su valor más probable", "El promedio ponderado por probabilidad de sus valores", "Su valor máximo", "Siempre un entero"], correct: 1 }, { q: "La linealidad de la esperanza, E[X+Y] = E[X] + E[Y], vale:", opts: ["Solo si X e Y son independientes", "Siempre, sean o no independientes", "Solo con dados", "Nunca"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función esperanza(dist) que reciba un dict {valor: prob} y devuelva E[X] = Σ valor·prob redondeada a 4 decimales.",
        starter: "def esperanza(dist):\n    # tu código acá\n    pass",
        tests: "assert esperanza({0: 0.1, 1: 0.2, 2: 0.4, 3: 0.2, 4: 0.1}) == 2.0, \"Demanda esperada 2.0\"\nassert esperanza({1: 0.5, 2: 0.5}) == 1.5, \"Promedio simple\"\nassert esperanza({7: 1.0}) == 7.0, \"Variable constante\"\nprint(\"TESTS_OK\")",
      },
    },
    M24: {
      code: "M24",
      materia: "Matemática Discreta",
      title: "Desviaciones y paseos aleatorios",
      fuente: "MIT 6.042J — Lec 24: Large deviations + Lec 25: Random walks | Libro LLM cap. 20-21",
      theory: ["¿Qué tan lejos de su esperanza puede caer una variable? La desigualdad de Markov da la primera cota: si X ≥ 0, entonces P(X ≥ a) ≤ E[X]/a. Con demanda esperada 2, la probabilidad de que un día pidan 10 o más es a lo sumo 2/10 = 0.2 — sin saber nada más de la distribución.", "La clase 25 cierra con paseos aleatorios: un valor que sube o baja al azar en cada paso. Es el modelo del jugador que apuesta hasta quebrar (\"gambler's ruin\") — y la matemática detrás del PageRank de Google, que la clase menciona como aplicación estrella. Simular mil paseos y promediar es tu primera herramienta de análisis probabilístico computacional."],
      example: "# Paseo aleatorio reproducible: caja que sube o baja $1 por operación\nimport random\nrandom.seed(42)\nsaldo, historia = 100, []\nfor _ in range(20):\n    saldo += random.choice([-1, 1])\n    historia.append(saldo)\nprint(\"Saldo final tras 20 pasos:\", saldo)\nprint(\"Mínimo del recorrido:\", min(historia))",
      quiz: [{ q: "La desigualdad de Markov (X ≥ 0) dice que P(X ≥ a) es a lo sumo:", opts: ["a / E[X]", "E[X] / a", "E[X] · a", "1 − E[X]"], correct: 1 }, { q: "Un paseo aleatorio es:", opts: ["Un valor que sube o baja al azar en cada paso", "Una caminata determinística", "Un grafo sin ciclos", "Una suma geométrica"], correct: 0 }],
      exercise: {
        prompt: "Escribí una función cota_markov(esperanza, a) que devuelva la cota superior de Markov para P(X ≥ a), es decir esperanza/a, redondeada a 4 decimales.",
        starter: "def cota_markov(esperanza, a):\n    # tu código acá\n    pass",
        tests: "assert cota_markov(2, 10) == 0.2, \"Demanda esperada 2, cota para >=10\"\nassert cota_markov(3, 4) == 0.75, \"Fallo caso 2\"\nassert cota_markov(5, 5) == 1.0, \"Cota trivial cuando a = E[X]\"\nprint(\"TESTS_OK\")",
      },
    },
    M25: {
      code: "M25",
      materia: "Matemática Discreta",
      title: "Proyecto integrador",
      fuente: "MIT 6.042J — Problem sets 6, 8 y 12 + exámenes con solución de OCW (nivel de exigencia)",
      theory: ["Este integrador junta las tres partes del curso, igual que los exámenes de 6.042J: estructuras discretas (grafos y conectividad), conteo, y probabilidad (distribuciones y esperanza). No hay teoría nueva: hay un problema con varias piezas.", "El caso: una red de sucursales conectadas por rutas, cada una con su distribución de demanda diaria. Hay que responder preguntas de conectividad (¿la mercadería llega?) y de planificación (¿cuánta demanda total esperar?) — grafos de M10-M13 más esperanza de M22-M23, en una sola función."],
      example: "# Las dos piezas del integrador, por separado\ngrafo = {\"Deposito\": [\"Norte\"], \"Norte\": [\"Deposito\", \"Sur\"], \"Sur\": [\"Norte\"]}\ndemandas = {\"Norte\": {1: 0.5, 2: 0.5}, \"Sur\": {2: 0.3, 3: 0.7}}\n\ne_total = sum(sum(v * p for v, p in dist.items()) for dist in demandas.values())\nprint(f\"Demanda total esperada por día: {e_total}\")",
      quiz: [{ q: "El integrador combina principalmente:", opts: ["Solo grafos", "Grafos/conectividad + esperanza de variables aleatorias", "Solo probabilidad", "Teoría de números"], correct: 1 }],
      exercise: {
        prompt: "Escribí una función plan_reparto(grafo, demandas, deposito) que devuelva un dict con: 'alcanzables' (set de sucursales de demandas a las que hay camino desde deposito, usá el patrón de M13) y 'demanda_esperada' (suma de las esperanzas de las distribuciones SOLO de las sucursales alcanzables, redondeada a 4 decimales).",
        starter: "def plan_reparto(grafo, demandas, deposito):\n    # tu código acá\n    pass",
        tests: "g = {\"D\": [\"N\"], \"N\": [\"D\", \"S\"], \"S\": [\"N\"], \"X\": []}\ndem = {\"N\": {1: 0.5, 2: 0.5}, \"S\": {2: 1.0}, \"X\": {9: 1.0}}\nr = plan_reparto(g, dem, \"D\")\nassert r[\"alcanzables\"] == {\"N\", \"S\"}, \"X está aislada, no debe entrar\"\nassert r[\"demanda_esperada\"] == 3.5, \"E[N]=1.5 + E[S]=2.0\"\nr2 = plan_reparto({\"D\": []}, dem, \"D\")\nassert r2[\"alcanzables\"] == set() and r2[\"demanda_esperada\"] == 0, \"Depósito aislado\"\nprint(\"TESTS_OK\")",
      },
    },
  },