  PRG2: {
    P01: {
      code: "P01",
      materia: "Estructuras de Datos",
      title: "Análisis de costo y notación O",
      fuente: "Princeton Algorithms Part I — Week 1: Analysis of Algorithms | Libro §1.4",
      theory: ["Antes de elegir una estructura hay que saber medir su costo. La notación O describe cómo crece el tiempo (o la memoria) de un algoritmo cuando la entrada n se agranda, ignorando constantes: recorrer una lista es O(n), y dos loops anidados son O(n²). Ya viste esto en MDIS M15; acá se vuelve la herramienta de trabajo diaria.", "El método de Sedgewick es científico: medís tiempos reales, formulás una hipótesis (\"esto es O(n²)\") y la verificás. La clave práctica: cuando n se duplica, un algoritmo O(n) tarda el doble, uno O(n²) tarda 4 veces más, y uno O(2ⁿ) se vuelve inusable. Elegir bien la estructura es elegir bien el exponente."],
      example: "# Contar operaciones: lineal O(n) vs cuadrático O(n²)\ndef operaciones_lineales(n):\n    ops = 0\n    for i in range(n):\n        ops += 1\n    return ops\n\ndef operaciones_cuadraticas(n):\n    ops = 0\n    for i in range(n):\n        for j in range(n):\n            ops += 1\n    return ops\n\nfor n in [10, 100]:\n    print(f\"n={n}: lineal={operaciones_lineales(n)}, cuadrático={operaciones_cuadraticas(n)}\")",
      quiz: [{ q: "Si un algoritmo es O(n²) y n se duplica, el tiempo se multiplica por:", opts: ["2", "4", "8", "No cambia"], correct: 1 }, { q: "Recorrer una lista de n elementos una sola vez es:", opts: ["O(1)", "O(n)", "O(n²)", "O(log n)"], correct: 1 }],
      exercise: {
        prompt: "Un algoritmo con dos loops anidados sobre n elementos hace n² operaciones. Escribí costo_cuadratico(n) que devuelva exactamente cuántas operaciones hace (n²), contándolas con loops reales (no uses n**2 directo).",
        starter: "def costo_cuadratico(n):\n    # tu código acá (contá con dos loops anidados)\n    pass",
        tests: "assert costo_cuadratico(3) == 9, \"3x3\"\nassert costo_cuadratico(10) == 100, \"10x10\"\nassert costo_cuadratico(0) == 0, \"Sin elementos\"\nprint(\"TESTS_OK\")",
      },
    },
    P02: {
      code: "P02",
      materia: "Estructuras de Datos",
      title: "Union-Find: conectividad dinámica",
      fuente: "Princeton Algorithms Part I — Week 1: Union-Find | Libro §1.5",
      theory: ["Union-Find resuelve la pregunta \"¿están estos dos elementos conectados?\" cuando las conexiones se van agregando de a una. Es el primer algoritmo del curso de Sedgewick, y modela cosas como: ¿estas dos sucursales están en la misma red de reparto?, ¿estos dos puntos de una grilla están conectados por agua? (el problema de percolación).", "La idea base (quick-find): cada elemento tiene un identificador de grupo. Están conectados si comparten identificador. Unir dos grupos es reasignar todos los del grupo de uno al del otro. Sedgewick muestra cómo las versiones mejoradas (quick-union, con pesos y compresión de caminos) bajan drásticamente el costo — el corazón de la Semana 1."],
      example: "# Quick-find: id[i] es el grupo del elemento i\nids = list(range(5))  # 5 elementos, cada uno en su propio grupo: [0,1,2,3,4]\n\ndef conectados(ids, p, q):\n    return ids[p] == ids[q]\n\ndef unir(ids, p, q):\n    grupo_p = ids[p]\n    grupo_q = ids[q]\n    for i in range(len(ids)):\n        if ids[i] == grupo_p:\n            ids[i] = grupo_q\n\nprint(\"¿0 y 2 conectados?:\", conectados(ids, 0, 2))  # False\nunir(ids, 0, 2)\nprint(\"Tras unir(0,2):\", conectados(ids, 0, 2))       # True",
      quiz: [{ q: "¿Qué pregunta resuelve Union-Find?", opts: ["Ordenar elementos", "Si dos elementos están conectados", "Buscar el máximo", "Contar duplicados"], correct: 1 }, { q: "En quick-find, dos elementos están conectados si:", opts: ["Son iguales", "Comparten el mismo identificador de grupo", "Son vecinos en la lista", "Su suma es par"], correct: 1 }],
      exercise: {
        prompt: "Implementá quick-find. Escribí unir(ids, p, q) que reciba la lista de identificadores y conecte p con q reasignando todos los del grupo de p al grupo de q. Devolvé la lista modificada.",
        starter: "def unir(ids, p, q):\n    # tu código acá\n    pass",
        tests: "ids = [0, 1, 2, 3, 4]\nids = unir(ids, 0, 2)\nassert ids[0] == ids[2], \"0 y 2 deben quedar conectados\"\nids = unir(ids, 2, 4)\nassert ids[0] == ids[4], \"Transitividad: 0 conectado con 4\"\nprint(\"TESTS_OK\")",
      },
    },
    P03: {
      code: "P03",
      materia: "Estructuras de Datos",
      title: "Pilas (stacks)",
      fuente: "Princeton Algorithms Part I — Week 2: Stacks and Queues | Libro §1.3",
      theory: ["Una pila es una colección LIFO: \"último en entrar, primero en salir\", como una pila de platos. Solo dos operaciones: push (apilar arriba) y pop (sacar el de arriba). Sedgewick la presenta como una de las dos estructuras fundamentales para guardar colecciones.", "¿Dónde aparece? En el \"deshacer\" de cualquier programa (Ctrl+Z saca la última acción), en la evaluación de expresiones, y en el recorrido de estructuras. En Python una lista con append (push) y pop() ya se comporta como pila — pero el punto es entender la mecánica LIFO, no solo usarla."],
      example: "# Pila con lista: append = push, pop = sacar el último\npila = []\npila.append(\"abrir caja\")     # push\npila.append(\"contar stock\")   # push\npila.append(\"cerrar caja\")    # push\nprint(\"Último en entrar:\", pila[-1])\nprint(\"Sale:\", pila.pop())    # \"cerrar caja\" (LIFO)\nprint(\"Ahora arriba:\", pila[-1])",
      quiz: [{ q: "Una pila (stack) sigue el orden:", opts: ["Primero en entrar, primero en salir", "Último en entrar, primero en salir (LIFO)", "Por prioridad", "Aleatorio"], correct: 1 }, { q: "El 'deshacer' (Ctrl+Z) de un programa se modela naturalmente con:", opts: ["Una cola", "Una pila", "Un árbol", "Una tabla hash"], correct: 1 }],
      exercise: {
        prompt: "Implementá la operación pop de una pila. Escribí pop(pila) que quite y devuelva el último elemento de la lista pila (el de arriba). Si la pila está vacía, devolvé None.",
        starter: "def pop(pila):\n    # tu código acá\n    pass",
        tests: "p = [\"a\", \"b\", \"c\"]\nassert pop(p) == \"c\", \"Sale el último (LIFO)\"\nassert p == [\"a\", \"b\"], \"La pila queda sin el último\"\nassert pop([]) is None, \"Pila vacía devuelve None\"\nprint(\"TESTS_OK\")",
      },
    },
    P04: {
      code: "P04",
      materia: "Estructuras de Datos",
      title: "Colas (queues)",
      fuente: "Princeton Algorithms Part I — Week 2: Stacks and Queues | Libro §1.3",
      theory: ["Una cola es una colección FIFO: \"primero en entrar, primero en salir\", como la fila del banco. Dos operaciones: enqueue (agregar al fondo) y dequeue (sacar del frente). Es la otra estructura fundamental de la Semana 2 de Sedgewick, opuesta a la pila.", "¿Dónde aparece? En cualquier cosa que se procese \"por orden de llegada\": pedidos en un local, tareas en una impresora, mensajes en un sistema. También es el motor del recorrido BFS de grafos que viste asomar en MDIS M13. La diferencia con la pila es solo de qué punta sacás."],
      example: "# Cola con lista: append al fondo, pop(0) del frente\ncola = []\ncola.append(\"pedido 1\")   # enqueue\ncola.append(\"pedido 2\")   # enqueue\ncola.append(\"pedido 3\")   # enqueue\nprint(\"Se atiende primero:\", cola[0])\nprint(\"Sale:\", cola.pop(0))  # \"pedido 1\" (FIFO)\nprint(\"Ahora al frente:\", cola[0])",
      quiz: [{ q: "Una cola (queue) sigue el orden:", opts: ["Último en entrar, primero en salir", "Primero en entrar, primero en salir (FIFO)", "Por prioridad", "Aleatorio"], correct: 1 }, { q: "La diferencia esencial entre pila y cola es:", opts: ["El tamaño máximo", "De qué extremo se saca el elemento", "El tipo de dato que guardan", "La velocidad"], correct: 1 }],
      exercise: {
        prompt: "Implementá la operación dequeue de una cola. Escribí dequeue(cola) que quite y devuelva el PRIMER elemento de la lista cola (el del frente, FIFO). Si está vacía, devolvé None.",
        starter: "def dequeue(cola):\n    # tu código acá\n    pass",
        tests: "c = [\"p1\", \"p2\", \"p3\"]\nassert dequeue(c) == \"p1\", \"Sale el primero (FIFO)\"\nassert c == [\"p2\", \"p3\"], \"La cola queda sin el primero\"\nassert dequeue([]) is None, \"Cola vacía devuelve None\"\nprint(\"TESTS_OK\")",
      },
    },
    P05: {
      code: "P05",
      materia: "Estructuras de Datos",
      title: "Listas enlazadas",
      fuente: "Princeton Algorithms Part I — Week 2: Stacks and Queues (implementación) | Libro §1.3",
      theory: ["Una lista enlazada guarda cada elemento en un \"nodo\" que apunta al siguiente, en vez de tenerlos contiguos como un array. Sedgewick la usa para implementar pilas y colas sin límite de tamaño fijo. La ventaja: insertar al principio es O(1) siempre. La desventaja: para llegar al elemento k hay que recorrer desde el inicio, O(n).", "En Python se modela con un dict o clase por nodo: {valor, siguiente}. No es que reemplace a la lista de Python (que es un array dinámico), sino que enseña el trade-off central de las estructuras: acceso rápido por posición (array) vs. inserción rápida en los extremos (lista enlazada)."],
      example: "# Lista enlazada con nodos {valor, sig}. Recorrerla siguiendo los punteros.\nnodo3 = {\"valor\": \"c\", \"sig\": None}\nnodo2 = {\"valor\": \"b\", \"sig\": nodo3}\nnodo1 = {\"valor\": \"a\", \"sig\": nodo2}  # cabeza\n\nactual = nodo1\nwhile actual is not None:\n    print(actual[\"valor\"])\n    actual = actual[\"sig\"]",
      quiz: [{ q: "En una lista enlazada, cada nodo guarda:", opts: ["Solo su valor", "Su valor y una referencia al siguiente nodo", "Todos los valores", "Un índice numérico"], correct: 1 }, { q: "Insertar al principio de una lista enlazada cuesta:", opts: ["O(n)", "O(1)", "O(n²)", "O(log n)"], correct: 1 }],
      exercise: {
        prompt: "Escribí longitud(cabeza) que recorra una lista enlazada de nodos {valor, sig} desde la cabeza y devuelva cuántos nodos tiene. Una cabeza None significa lista vacía (longitud 0).",
        starter: "def longitud(cabeza):\n    # tu código acá\n    pass",
        tests: "n3 = {\"valor\": \"c\", \"sig\": None}\nn2 = {\"valor\": \"b\", \"sig\": n3}\nn1 = {\"valor\": \"a\", \"sig\": n2}\nassert longitud(n1) == 3, \"3 nodos\"\nassert longitud(n3) == 1, \"1 nodo\"\nassert longitud(None) == 0, \"Lista vacía\"\nprint(\"TESTS_OK\")",
      },
    },
    P06: {
      code: "P06",
      materia: "Estructuras de Datos",
      title: "Ordenamientos elementales",
      fuente: "Princeton Algorithms Part I — Week 2: Elementary Sorts | Libro §2.1",
      theory: ["Los primeros ordenamientos de Sedgewick son selection sort e insertion sort, ambos O(n²). Selection sort busca el mínimo y lo pone al principio, repitiendo con el resto. Insertion sort va tomando cada elemento y lo inserta en su lugar entre los ya ordenados, como cuando ordenás cartas en la mano.", "Son \"lentos\" (O(n²)) pero valen oro pedagógicamente: enseñan el patrón de comparar-e-intercambiar y sirven de baseline. Insertion sort además es rapidísimo cuando la lista ya está casi ordenada — un detalle que Sedgewick aprovecha en los algoritmos avanzados. Los rápidos (O(n log n)) vienen en las próximas lecciones."],
      example: "# Selection sort: buscar el mínimo y ponerlo adelante, repetir\ndef selection_sort(a):\n    a = a[:]  # copia para no mutar el original\n    for i in range(len(a)):\n        min_idx = i\n        for j in range(i + 1, len(a)):\n            if a[j] < a[min_idx]:\n                min_idx = j\n        a[i], a[min_idx] = a[min_idx], a[i]\n    return a\n\nprint(selection_sort([40, 12, 8, 25, 3]))",
      quiz: [{ q: "Selection sort e insertion sort tienen costo:", opts: ["O(n)", "O(n log n)", "O(n²)", "O(1)"], correct: 2 }, { q: "¿Qué hace selection sort en cada paso?", opts: ["Divide la lista al medio", "Busca el mínimo del resto y lo pone en su lugar", "Compara con un pivote", "Usa una tabla hash"], correct: 1 }],
      exercise: {
        prompt: "Implementá selection sort. Escribí selection_sort(a) que devuelva una NUEVA lista con los elementos de a ordenados de menor a mayor, usando el método de buscar el mínimo (no uses sorted() ni .sort()).",
        starter: "def selection_sort(a):\n    # tu código acá\n    pass",
        tests: "assert selection_sort([3, 1, 2]) == [1, 2, 3], \"Orden básico\"\nassert selection_sort([40, 12, 8, 25, 3]) == [3, 8, 12, 25, 40], \"Caso 5 elementos\"\nassert selection_sort([]) == [], \"Lista vacía\"\nprint(\"TESTS_OK\")",
      },
    },
    P07: {
      code: "P07",
      materia: "Estructuras de Datos",
      title: "Mergesort",
      fuente: "Princeton Algorithms Part I — Week 3: Mergesort | Libro §2.2",
      theory: ["Mergesort es el primer ordenamiento rápido de Sedgewick: O(n log n). Usa divide y vencerás (la recurrencia que viste en MDIS M16): parte la lista al medio, ordena cada mitad recursivamente, y después MEZCLA (merge) las dos mitades ordenadas en una sola. La magia está en el merge: fusionar dos listas ya ordenadas es O(n).", "El costo O(n log n) sale de la recurrencia T(n) = 2·T(n/2) + n: hay log n niveles de división y cada nivel cuesta n en mezclar. Es la garantía de mergesort: SIEMPRE O(n log n), sin importar cómo venga la entrada. Su desventaja es que necesita memoria extra para la mezcla."],
      example: "# El corazón de mergesort: mezclar dos listas ya ordenadas\ndef merge(izq, der):\n    resultado = []\n    i = j = 0\n    while i < len(izq) and j < len(der):\n        if izq[i] <= der[j]:\n            resultado.append(izq[i]); i += 1\n        else:\n            resultado.append(der[j]); j += 1\n    resultado.extend(izq[i:])\n    resultado.extend(der[j:])\n    return resultado\n\nprint(merge([1, 4, 8], [2, 3, 9]))  # [1, 2, 3, 4, 8, 9]",
      quiz: [{ q: "Mergesort tiene costo:", opts: ["O(n²)", "O(n log n) siempre", "O(n)", "O(2ⁿ)"], correct: 1 }, { q: "El paso 'merge' de mergesort:", opts: ["Divide la lista", "Fusiona dos listas ya ordenadas en O(n)", "Busca el mínimo", "Usa un pivote"], correct: 1 }],
      exercise: {
        prompt: "Implementá el paso merge. Escribí merge(izq, der) que reciba dos listas YA ordenadas y devuelva una sola lista ordenada con todos sus elementos, recorriéndolas en paralelo (no uses sorted()).",
        starter: "def merge(izq, der):\n    # tu código acá\n    pass",
        tests: "assert merge([1,4,8], [2,3,9]) == [1,2,3,4,8,9], \"Mezcla intercalada\"\nassert merge([], [1,2]) == [1,2], \"Una vacía\"\nassert merge([5], [1]) == [1,5], \"Un elemento cada una\"\nprint(\"TESTS_OK\")",
      },
    },
    P08: {
      code: "P08",
      materia: "Estructuras de Datos",
      title: "Quicksort",
      fuente: "Princeton Algorithms Part I — Week 3: Quicksort | Libro §2.3",
      theory: ["Quicksort es el otro gran ordenamiento de la Semana 3, y el más usado en la práctica. Elige un pivote, particiona la lista en \"menores que el pivote\" y \"mayores que el pivote\", y ordena cada parte recursivamente. En promedio es O(n log n) y usa poca memoria extra — por eso es el default de muchas librerías.", "El detalle que Sedgewick remarca: su peor caso es O(n²) (si el pivote siempre resulta el peor posible), pero elegir el pivote al azar lo vuelve improbable. La diferencia con mergesort: quicksort particiona ANTES de recursión (el trabajo está en dividir bien), mergesort mezcla DESPUÉS (el trabajo está en combinar)."],
      example: "# Partición: separar en menores y mayores que el pivote\ndef particionar(a, pivote):\n    menores = [x for x in a if x < pivote]\n    iguales = [x for x in a if x == pivote]\n    mayores = [x for x in a if x > pivote]\n    return menores, iguales, mayores\n\nmen, ig, may = particionar([40, 12, 8, 25, 3], 12)\nprint(\"Menores:\", men, \"| Iguales:\", ig, \"| Mayores:\", may)",
      quiz: [{ q: "Quicksort ordena:", opts: ["Buscando el mínimo cada vez", "Particionando alrededor de un pivote y recurriendo", "Mezclando mitades ordenadas", "Con una tabla hash"], correct: 1 }, { q: "El peor caso de quicksort es O(n²), pero se evita en la práctica:", opts: ["Usando más memoria", "Eligiendo el pivote al azar", "Ordenando dos veces", "No se puede evitar"], correct: 1 }],
      exercise: {
        prompt: "Implementá quicksort. Escribí quicksort(a) que devuelva una nueva lista ordenada, eligiendo como pivote el primer elemento y usando particiones (menores, iguales, mayores) con recursión. No uses sorted().",
        starter: "def quicksort(a):\n    # tu código acá (caso base: lista de 0 o 1 elemento ya está ordenada)\n    pass",
        tests: "assert quicksort([3, 1, 2]) == [1, 2, 3], \"Orden básico\"\nassert quicksort([40, 12, 8, 25, 3]) == [3, 8, 12, 25, 40], \"5 elementos\"\nassert quicksort([5, 5, 1]) == [1, 5, 5], \"Con repetidos\"\nassert quicksort([]) == [], \"Vacía\"\nprint(\"TESTS_OK\")",
      },
    },
    P09: {
      code: "P09",
      materia: "Estructuras de Datos",
      title: "Colas de prioridad y heaps",
      fuente: "Princeton Algorithms Part I — Week 4: Priority Queues | Libro §2.4",
      theory: ["Una cola de prioridad no saca el primero que entró (como la cola normal) ni el último (como la pila), sino el de MAYOR prioridad. Sedgewick la implementa con un heap binario: un árbol donde cada padre es mayor (o menor) que sus hijos, lo que deja el elemento prioritario siempre en la raíz.", "Lo potente del heap: insertar y sacar el máximo son ambos O(log n), mucho mejor que buscar el máximo en una lista (O(n)) cada vez. Aparece en todo lo que procesa \"lo más urgente primero\": pedidos por prioridad, el algoritmo de Dijkstra (que verás en ALGO), y la compresión de datos."],
      example: "# El máximo de un heap está en la raíz. Simulamos con el módulo heapq (min-heap).\nimport heapq\ntareas = []\nheapq.heappush(tareas, (2, \"reponer stock\"))   # (prioridad, tarea)\nheapq.heappush(tareas, (1, \"cerrar caja\"))      # prioridad 1 = más urgente\nheapq.heappush(tareas, (3, \"limpiar\"))\nprint(\"Más urgente:\", heapq.heappop(tareas))    # (1, \"cerrar caja\")",
      quiz: [{ q: "Una cola de prioridad saca siempre:", opts: ["El primero que entró", "El último que entró", "El de mayor prioridad", "Uno al azar"], correct: 2 }, { q: "Insertar y sacar el máximo en un heap binario cuestan:", opts: ["O(1)", "O(log n)", "O(n)", "O(n²)"], correct: 1 }],
      exercise: {
        prompt: "Sin usar heapq: escribí sacar_maximo(a) que reciba una lista de números, quite y devuelva el máximo (simulando el 'pop' de una cola de prioridad de máximo). Si está vacía, devolvé None. La lista queda sin ese elemento.",
        starter: "def sacar_maximo(a):\n    # tu código acá\n    pass",
        tests: "lista = [3, 7, 2, 7, 1]\nassert sacar_maximo(lista) == 7, \"El máximo\"\nassert lista.count(7) == 1, \"Quitó solo una ocurrencia del máximo\"\nassert sacar_maximo([]) is None, \"Vacía devuelve None\"\nprint(\"TESTS_OK\")",
      },
    },
    P10: {
      code: "P10",
      materia: "Estructuras de Datos",
      title: "Heapsort",
      fuente: "Princeton Algorithms Part I — Week 4: Priority Queues (heapsort) | Libro §2.4",
      theory: ["Heapsort ordena usando la idea de la cola de prioridad: metés todos los elementos en un heap y los vas sacando de a uno; como cada extracción da el máximo (o mínimo), salen ordenados. Es O(n log n), como mergesort y quicksort.", "Su ventaja sobre mergesort: ordena \"in place\", sin memoria extra significativa. Su desventaja frente a quicksort: suele ser más lento en la práctica por cómo accede a memoria. Sedgewick lo presenta como el cierre natural del tema de heaps: la estructura que sirve para priorizar también sirve para ordenar."],
      example: "# Heapsort conceptual: sacar repetidamente el mínimo de un heap\nimport heapq\ndef heapsort(a):\n    h = a[:]\n    heapq.heapify(h)          # convierte la lista en heap: O(n)\n    return [heapq.heappop(h) for _ in range(len(h))]\n\nprint(heapsort([40, 12, 8, 25, 3]))  # [3, 8, 12, 25, 40]",
      quiz: [{ q: "Heapsort ordena:", opts: ["Buscando el mínimo linealmente", "Metiendo todo en un heap y sacándolo de a uno", "Con un pivote", "Mezclando mitades"], correct: 1 }, { q: "La ventaja de heapsort sobre mergesort es:", opts: ["Es más simple", "Ordena in place, sin memoria extra significativa", "Es siempre más rápido", "No necesita comparaciones"], correct: 1 }],
      exercise: {
        prompt: "Implementá heapsort usando heapq. Escribí heapsort(a) que devuelva una nueva lista ordenada de menor a mayor, convirtiendo a en heap y sacando los elementos de a uno. No uses sorted() ni .sort().",
        starter: "import heapq\n\ndef heapsort(a):\n    # tu código acá\n    pass",
        tests: "assert heapsort([3, 1, 2]) == [1, 2, 3], \"Orden básico\"\nassert heapsort([40, 12, 8, 25, 3]) == [3, 8, 12, 25, 40], \"5 elementos\"\nassert heapsort([]) == [], \"Vacía\"\nprint(\"TESTS_OK\")",
      },
    },
    P11: {
      code: "P11",
      materia: "Estructuras de Datos",
      title: "Tablas de símbolos y búsqueda binaria",
      fuente: "Princeton Algorithms Part I — Week 4: Elementary Symbol Tables | Libro §3.1",
      theory: ["Una tabla de símbolos asocia claves con valores — es el concepto abstracto detrás del diccionario de Python y de cualquier índice. Sedgewick arranca con la implementación sobre un array ordenado, donde buscar una clave se hace con búsqueda binaria.", "La búsqueda binaria es la joya: en una lista ORDENADA, en vez de mirar elemento por elemento (O(n)), mirás el del medio y descartás la mitad que no puede contener la clave, repitiendo. Eso da O(log n): en un millón de elementos, unas 20 comparaciones. La condición es que esté ordenada — por eso ordenar importa tanto."],
      example: "# Búsqueda binaria: descartar la mitad en cada paso (lista ordenada)\ndef busqueda_binaria(a, clave):\n    lo, hi = 0, len(a) - 1\n    while lo <= hi:\n        medio = (lo + hi) // 2\n        if a[medio] == clave:\n            return medio\n        elif a[medio] < clave:\n            lo = medio + 1\n        else:\n            hi = medio - 1\n    return -1  # no está\n\nprint(\"Índice de 25:\", busqueda_binaria([3, 8, 12, 25, 40], 25))  # 3\nprint(\"Índice de 7:\", busqueda_binaria([3, 8, 12, 25, 40], 7))    # -1",
      quiz: [{ q: "La búsqueda binaria requiere que la lista esté:", opts: ["Vacía", "Ordenada", "Sin repetidos", "Al revés"], correct: 1 }, { q: "La búsqueda binaria en n elementos cuesta:", opts: ["O(n)", "O(log n)", "O(n²)", "O(1)"], correct: 1 }],
      exercise: {
        prompt: "Implementá búsqueda binaria. Escribí busqueda_binaria(a, clave) que reciba una lista ORDENADA y devuelva el índice de clave, o -1 si no está, descartando la mitad en cada paso.",
        starter: "def busqueda_binaria(a, clave):\n    # tu código acá\n    pass",
        tests: "assert busqueda_binaria([3,8,12,25,40], 25) == 3, \"Encuentra 25\"\nassert busqueda_binaria([3,8,12,25,40], 3) == 0, \"Primer elemento\"\nassert busqueda_binaria([3,8,12,25,40], 7) == -1, \"No está\"\nassert busqueda_binaria([], 5) == -1, \"Lista vacía\"\nprint(\"TESTS_OK\")",
      },
    },
    P12: {
      code: "P12",
      materia: "Estructuras de Datos",
      title: "Árboles binarios de búsqueda (BST)",
      fuente: "Princeton Algorithms Part I — Week 4: BSTs | Libro §3.2",
      theory: ["Un árbol binario de búsqueda (BST) organiza claves de modo que, en cada nodo, todo lo menor va a la izquierda y todo lo mayor a la derecha. Retomás los árboles de MDIS M12, ahora con una regla de orden que hace la búsqueda eficiente: en promedio O(log n), porque cada comparación descarta un subárbol entero.", "La ventaja sobre el array ordenado (P11): en un BST insertar también es O(log n) en promedio, mientras que en un array ordenado insertar es O(n) porque hay que correr elementos. La trampa, que Sedgewick remarca: si insertás claves ya ordenadas, el BST degenera en una lista (O(n)) — lo que motiva los árboles balanceados de la próxima lección."],
      example: "# BST con nodos {clave, izq, der}. Insertar respeta menor-izquierda, mayor-derecha.\ndef insertar(nodo, clave):\n    if nodo is None:\n        return {\"clave\": clave, \"izq\": None, \"der\": None}\n    if clave < nodo[\"clave\"]:\n        nodo[\"izq\"] = insertar(nodo[\"izq\"], clave)\n    elif clave > nodo[\"clave\"]:\n        nodo[\"der\"] = insertar(nodo[\"der\"], clave)\n    return nodo\n\nraiz = None\nfor c in [25, 12, 40, 8]:\n    raiz = insertar(raiz, c)\nprint(\"Raíz:\", raiz[\"clave\"], \"| izq:\", raiz[\"izq\"][\"clave\"], \"| der:\", raiz[\"der\"][\"clave\"])",
      quiz: [{ q: "En un BST, comparado con un nodo, las claves menores van:", opts: ["A la derecha", "A la izquierda", "En la raíz", "Se descartan"], correct: 1 }, { q: "¿Por qué un BST puede degenerar a O(n)?", opts: ["Por usar mucha memoria", "Si se insertan claves ya ordenadas, queda como una lista", "Por tener claves repetidas", "Nunca degenera"], correct: 1 }],
      exercise: {
        prompt: "Escribí buscar(nodo, clave) que busque una clave en un BST de nodos {clave, izq, der} y devuelva True si está, False si no. Aprovechá el orden: bajá a la izquierda si la clave es menor, a la derecha si es mayor.",
        starter: "def buscar(nodo, clave):\n    # tu código acá\n    pass",
        tests: "def insertar(nodo, clave):\n    if nodo is None: return {\"clave\": clave, \"izq\": None, \"der\": None}\n    if clave < nodo[\"clave\"]: nodo[\"izq\"] = insertar(nodo[\"izq\"], clave)\n    elif clave > nodo[\"clave\"]: nodo[\"der\"] = insertar(nodo[\"der\"], clave)\n    return nodo\nraiz = None\nfor c in [25, 12, 40, 8]: raiz = insertar(raiz, c)\nassert buscar(raiz, 40) == True, \"40 está\"\nassert buscar(raiz, 8) == True, \"8 está (hoja izquierda)\"\nassert buscar(raiz, 99) == False, \"99 no está\"\nassert buscar(None, 5) == False, \"Árbol vacío\"\nprint(\"TESTS_OK\")",
      },
    },
    P13: {
      code: "P13",
      materia: "Estructuras de Datos",
      title: "Árboles balanceados (panorama)",
      fuente: "Princeton Algorithms Part I — Week 5: Balanced Search Trees | Libro §3.3",
      theory: ["Un árbol balanceado se reorganiza automáticamente al insertar para que nunca degenere en lista: garantiza O(log n) SIEMPRE, no solo en promedio. Sedgewick enseña los árboles rojo-negro, que mantienen el balance con reglas de color en los nodos y rotaciones.", "No hace falta memorizar la mecánica de las rotaciones para entender el punto: es la solución al problema que dejó abierto el BST (P12). La altura de un árbol balanceado de n nodos es siempre ~log n, y esa altura es exactamente lo que cuesta buscar, insertar o borrar. En Python, el dict y el set usan hashing (próxima lección), pero muchas bases de datos usan árboles balanceados por debajo."],
      example: "# La altura de un árbol determina el costo. Balanceado: altura ~ log2(n).\nimport math\ndef altura_de_lista(nodo):\n    # BST degenerado (lista): altura = n\n    n = 0\n    while nodo is not None:\n        n += 1\n        nodo = nodo.get(\"der\")\n    return n\n\nfor n in [1, 15, 1023, 1_000_000]:\n    print(f\"n={n}: degenerado={n}, balanceado~{math.ceil(math.log2(n+1))}\")",
      quiz: [{ q: "La ventaja de un árbol balanceado sobre un BST común es:", opts: ["Usa menos memoria", "Garantiza O(log n) siempre, sin degenerar", "No necesita comparaciones", "Es más fácil de programar"], correct: 1 }, { q: "La altura de un árbol balanceado con n nodos es aproximadamente:", opts: ["n", "n²", "log n", "1"], correct: 2 }],
      exercise: {
        prompt: "La altura de un árbol balanceado con n nodos es ceil(log2(n+1)). Escribí altura_balanceada(n) que la devuelva como entero. Para n=0 devolvé 0.",
        starter: "import math\n\ndef altura_balanceada(n):\n    # tu código acá\n    pass",
        tests: "assert altura_balanceada(1) == 1, \"1 nodo, altura 1\"\nassert altura_balanceada(7) == 3, \"7 nodos, altura 3\"\nassert altura_balanceada(0) == 0, \"Árbol vacío\"\nprint(\"TESTS_OK\")",
      },
    },
    P14: {
      code: "P14",
      materia: "Estructuras de Datos",
      title: "Tablas hash",
      fuente: "Princeton Algorithms Part I — Week 6: Hash Tables | Libro §3.4",
      theory: ["Una tabla hash logra búsqueda e inserción en O(1) promedio — más rápido que cualquier árbol. La idea: una función hash convierte la clave en un número (un índice de un array), y ahí se guarda el valor. Es la estructura detrás del dict y el set de Python.", "El problema son las colisiones: dos claves distintas que caen en el mismo índice. Sedgewick enseña dos soluciones — encadenamiento (guardar una lista en cada índice) y sondeo lineal (buscar el siguiente hueco libre). El costo O(1) depende de una buena función hash que reparta parejo; con una mala, todo colisiona y degenera a O(n)."],
      example: "# Hash simple: índice = clave % tamaño. Colisión = mismo índice.\ndef indice_hash(clave, tamano):\n    return hash(clave) % tamano\n\ntamano = 5\nfor palabra in [\"gaseosa\", \"agua\", \"snack\"]:\n    print(f\"{palabra} -> índice {indice_hash(palabra, tamano)}\")",
      quiz: [{ q: "Una tabla hash logra búsqueda en:", opts: ["O(log n)", "O(1) promedio", "O(n)", "O(n²)"], correct: 1 }, { q: "Una colisión en una tabla hash es cuando:", opts: ["La tabla se llena", "Dos claves distintas caen en el mismo índice", "La clave no existe", "El hash es negativo"], correct: 1 }],
      exercise: {
        prompt: "Implementá una tabla hash con encadenamiento simple. Escribí insertar(tabla, clave, valor) donde tabla es una lista de listas (buckets). Calculá el índice con hash(clave) % len(tabla) y agregá el par (clave, valor) a ese bucket. Devolvé la tabla.",
        starter: "def insertar(tabla, clave, valor):\n    # tu código acá\n    pass",
        tests: "tabla = [[] for _ in range(4)]\ninsertar(tabla, \"a\", 1)\ninsertar(tabla, \"b\", 2)\n# el par debe estar en el bucket correspondiente al hash\nidx_a = hash(\"a\") % 4\nassert (\"a\", 1) in tabla[idx_a], \"El par (a,1) debe estar en su bucket\"\ntotal = sum(len(b) for b in tabla)\nassert total == 2, \"Dos pares insertados en total\"\nprint(\"TESTS_OK\")",
      },
    },
    P15: {
      code: "P15",
      materia: "Estructuras de Datos",
      title: "Aplicaciones de tablas de símbolos",
      fuente: "Princeton Algorithms Part I — Week 6: Symbol Table Applications | Libro §3.5",
      theory: ["Con tablas de símbolos (dicts/hash) se resuelven elegantemente problemas que serían O(n²) a fuerza bruta. El ejemplo clásico de Sedgewick: contar frecuencias. Recorrés los datos una vez, y por cada elemento incrementás su contador en la tabla — O(n) total en vez de contar cada uno recorriendo todo.", "Es el patrón más útil del día a día: detectar duplicados, agrupar por categoría, indexar. En tu ERP: contar cuántas ventas hubo por producto, o agrupar pedidos por sucursal, es exactamente esto. La tabla de símbolos convierte búsquedas repetidas en accesos O(1)."],
      example: "# Contar frecuencias con un dict: O(n) en una pasada\ndef frecuencias(datos):\n    conteo = {}\n    for x in datos:\n        conteo[x] = conteo.get(x, 0) + 1\n    return conteo\n\nventas = [\"gaseosa\", \"agua\", \"gaseosa\", \"snack\", \"gaseosa\"]\nprint(frecuencias(ventas))  # {'gaseosa': 3, 'agua': 1, 'snack': 1}",
      quiz: [{ q: "Contar frecuencias con una tabla de símbolos cuesta:", opts: ["O(n²)", "O(n)", "O(log n)", "O(1)"], correct: 1 }, { q: "El patrón 'agrupar por categoría' se resuelve naturalmente con:", opts: ["Una pila", "Una cola", "Una tabla de símbolos (dict)", "Un heap"], correct: 2 }],
      exercise: {
        prompt: "Escribí mas_frecuente(datos) que reciba una lista y devuelva el elemento que más veces aparece, usando un dict de conteo. Si hay empate, devolvé cualquiera de los máximos. Lista vacía devuelve None.",
        starter: "def mas_frecuente(datos):\n    # tu código acá\n    pass",
        tests: "assert mas_frecuente([\"a\",\"b\",\"a\",\"a\"]) == \"a\", \"a aparece 3 veces\"\nassert mas_frecuente([1]) == 1, \"Un solo elemento\"\nassert mas_frecuente([]) is None, \"Lista vacía\"\nprint(\"TESTS_OK\")",
      },
    },
    P16: {
      code: "P16",
      materia: "Estructuras de Datos",
      title: "Elegir la estructura adecuada (síntesis)",
      fuente: "Princeton Algorithms Part I — Síntesis del curso | Libro cap. 1-3",
      theory: ["El verdadero aprendizaje de la materia no es implementar cada estructura, sino saber CUÁL usar. La regla: pila para LIFO (deshacer), cola para FIFO (orden de llegada), cola de prioridad para \"lo más urgente\", tabla hash para búsqueda rápida por clave, BST/balanceado para búsqueda rápida MANTENIENDO orden.", "El criterio de Sedgewick es siempre el costo según la operación dominante: si vas a buscar mucho por clave sin importar el orden, hash (O(1)); si necesitás recorrer en orden o buscar rangos, árbol (O(log n) pero ordenado); si insertás/sacás solo por los extremos, pila o cola (O(1)). Elegir mal la estructura es la causa más común de un programa lento."],
      example: "# La misma tarea, distinta estructura según lo que importe\n# ¿Buscar rápido por clave? -> dict (hash). ¿Mantener orden? -> lista ordenada.\ninventario = {\"gaseosa\": 40, \"agua\": 12}   # hash: acceso O(1) por nombre\nprint(\"Stock de gaseosa (O(1)):\", inventario[\"gaseosa\"])\n\n# ¿Procesar lo más urgente? -> cola de prioridad\nimport heapq\nurgencias = [(2, \"reponer\"), (1, \"cerrar\")]\nheapq.heapify(urgencias)\nprint(\"Primero:\", heapq.heappop(urgencias))",
      quiz: [{ q: "Para buscar rápido por clave SIN importar el orden, conviene:", opts: ["Una pila", "Una tabla hash (dict)", "Una cola", "Una lista sin ordenar"], correct: 1 }, { q: "Para buscar rápido MANTENIENDO los elementos ordenados, conviene:", opts: ["Una tabla hash", "Un árbol de búsqueda balanceado", "Una pila", "Una cola"], correct: 1 }],
      exercise: {
        prompt: "Dado un caso, elegí la estructura. Escribí estructura_para(caso) que devuelva: 'pila' si caso=='deshacer', 'cola' si caso=='orden_llegada', 'prioridad' si caso=='mas_urgente', 'hash' si caso=='buscar_por_clave'. Para cualquier otro, 'lista'.",
        starter: "def estructura_para(caso):\n    # tu código acá\n    pass",
        tests: "assert estructura_para(\"deshacer\") == \"pila\", \"LIFO\"\nassert estructura_para(\"orden_llegada\") == \"cola\", \"FIFO\"\nassert estructura_para(\"mas_urgente\") == \"prioridad\", \"Cola de prioridad\"\nassert estructura_para(\"buscar_por_clave\") == \"hash\", \"Tabla hash\"\nassert estructura_para(\"otra_cosa\") == \"lista\", \"Default\"\nprint(\"TESTS_OK\")",
      },
    },
    P17: {
      code: "P17",
      materia: "Estructuras de Datos",
      title: "Proyecto integrador",
      fuente: "Princeton Algorithms Part I — Programming assignments (nivel de exigencia) | Libro cap. 1-3",
      theory: ["Este integrador combina varias estructuras en un caso realista, al nivel de un programming assignment de Princeton. No hay tema nuevo: hay que elegir bien y componer lo aprendido.", "El caso: procesar pedidos que llegan con una prioridad, manteniendo además un índice para consultar rápido cuántos pedidos hay por cliente. Eso combina una cola de prioridad (para atender por urgencia) con una tabla de símbolos (para contar por cliente) — dos estructuras del curso trabajando juntas."],
      example: "# Las piezas del integrador: prioridad + conteo por clave\nimport heapq\npedidos = []\nheapq.heappush(pedidos, (1, \"urgente de cliente A\"))\nheapq.heappush(pedidos, (3, \"normal de cliente B\"))\nconteo = {\"A\": 1, \"B\": 1}\nprint(\"Atender primero:\", heapq.heappop(pedidos))\nprint(\"Pedidos de A:\", conteo[\"A\"])",
      quiz: [{ q: "El integrador combina cola de prioridad + tabla de símbolos para:", opts: ["Ordenar más rápido", "Atender por urgencia Y contar por cliente a la vez", "Ahorrar memoria", "Evitar colisiones"], correct: 1 }],
      exercise: {
        prompt: "Escribí resumen_pedidos(pedidos) que reciba una lista de tuplas (prioridad, cliente). Devolvé un dict con: 'primero' = el cliente del pedido de MENOR prioridad numérica (más urgente), y 'por_cliente' = un dict {cliente: cantidad de pedidos}. Si no hay pedidos, 'primero' es None y 'por_cliente' es {}.",
        starter: "def resumen_pedidos(pedidos):\n    # tu código acá\n    pass",
        tests: "p = [(3, \"B\"), (1, \"A\"), (2, \"A\")]\nr = resumen_pedidos(p)\nassert r[\"primero\"] == \"A\", \"El más urgente (prioridad 1) es de A\"\nassert r[\"por_cliente\"] == {\"B\": 1, \"A\": 2}, \"Conteo por cliente\"\nr2 = resumen_pedidos([])\nassert r2[\"primero\"] is None and r2[\"por_cliente\"] == {}, \"Sin pedidos\"\nprint(\"TESTS_OK\")",
      },
    },
  },